run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: max-public-structs
        disabled: true
      - name: file-header
        disabled: true
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

# Custom rules for function and file length
# Note: golangci-lint doesn't have built-in function/file length checks
# These would need to be checked manually or via custom scripts

