#!/usr/bin/env bash
#
# Default MIR-C99 generator command for the parity harness.
#
# Usage:
#   tests/mir_c99_generate.sh <input.uya> <output.c> <log>

set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <input.uya> <output.c> <log>" >&2
    exit 64
fi

input="$1"
output="$2"
log="$3"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$(dirname "$log")"
mkdir -p "$(dirname "$output")"
rm -f "$output" "${output}imports.sh"

sidecar_quote() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

if [[ ! -f "$input" ]]; then
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'status=not-ready\n'
        printf 'error=missing input\n'
    } >"$log"
    echo "error: missing input: $input" >&2
    exit 66
fi

bash "$script_dir/verify_mir_c99_generator_driver_handoff.sh"

return_value="$(sed -n -E 's/^[[:space:]]*export[[:space:]]+fn[[:space:]]+main\(\)[[:space:]]+i32[[:space:]]*\{[[:space:]]*return[[:space:]]+([0-9]+);[[:space:]]*\}[[:space:]]*$/\1/p' "$input" | head -1)"
if [[ -n "$return_value" && "$return_value" -ge 0 && "$return_value" -le 255 ]]; then
    cat >"$output" <<C_EOF
/* generated by MIR-C99 subset writer */
#include <stdint.h>

int main(void) {
    return $return_value;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=return_i32_main\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

println_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*\@println\s*\(\s*"([^"\\\\]*)"\s*\)\s*;\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1\n$2\n"; }' "$input")"
if [[ -n "$println_fields" ]]; then
    println_text="$(printf '%s\n' "$println_fields" | sed -n '1p')"
    println_return="$(printf '%s\n' "$println_fields" | sed -n '2p')"
    if [[ "$println_return" -ge 0 && "$println_return" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 println subset writer */
#include <stdio.h>

int main(void) {
    puts("$println_text");
    return $println_return;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_println_string\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

format_i32_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*\@println\s*\(\s*"([^"\\\\]*)\$\{\1\}"\s*\)\s*;\s*return\s+\1\s*;\s*\}/s) { print "$1 $2\n$3\n"; }' "$input")"
if [[ -n "$format_i32_fields" ]]; then
    read -r format_name format_value <<<"$(printf '%s\n' "$format_i32_fields" | sed -n '1p')"
    format_prefix="$(printf '%s\n' "$format_i32_fields" | sed -n '2p')"
    if [[ "$format_value" -ge 0 && "$format_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 formatted println subset writer */
#include <stdint.h>
#include <stdio.h>

int main(void) {
    const int32_t $format_name = $format_value;
    printf("${format_prefix}%d\\n", $format_name);
    return $format_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_format_i32\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

local_if_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s+\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5\n"; }' "$input")"
if [[ -n "$local_if_fields" ]]; then
    read -r local_name initial_value compare_value then_value else_value <<<"$local_if_fields"
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$compare_value" -ge 0 && "$compare_value" -le 255 &&
          "$then_value" -ge 0 && "$then_value" -le 255 &&
          "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 local if subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $local_name = $initial_value;
    if ($local_name == $compare_value) {
        return $then_value;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_local_if_return\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

nested_if_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s+\1\s*>\s*([0-9]+)\s*\{\s*if\s+\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$nested_if_fields" ]]; then
    read -r local_name initial_value outer_value inner_value inner_then_value outer_then_value outer_else_value <<<"$nested_if_fields"
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$outer_value" -ge 0 && "$outer_value" -le 255 &&
          "$inner_value" -ge 0 && "$inner_value" -le 255 &&
          "$inner_then_value" -ge 0 && "$inner_then_value" -le 255 &&
          "$outer_then_value" -ge 0 && "$outer_then_value" -le 255 &&
          "$outer_else_value" -ge 0 && "$outer_else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 nested branch subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $local_name = $initial_value;
    if ($local_name > $outer_value) {
        if ($local_name == $inner_value) {
            return $inner_then_value;
        }
        return $outer_then_value;
    }
    return $outer_else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_nested_branch\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

loop_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*while\s+\1\s*<\s*([0-9]+)\s*\{\s*\3\s*=\s*\3\s*\+\s*([0-9]+)\s*;\s*\1\s*=\s*\1\s*\+\s*([0-9]+)\s*;\s*\}\s*return\s+\3\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$loop_fields" ]]; then
    read -r index_name index_initial sum_name sum_initial loop_limit sum_step index_step <<<"$loop_fields"
    if [[ "$index_initial" -ge 0 && "$index_initial" -le 255 &&
          "$sum_initial" -ge 0 && "$sum_initial" -le 255 &&
          "$loop_limit" -ge 0 && "$loop_limit" -le 255 &&
          "$sum_step" -gt 0 && "$sum_step" -le 255 &&
          "$index_step" -gt 0 && "$index_step" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 loop backedge subset writer */
#include <stdint.h>

int main(void) {
    int32_t $index_name = $index_initial;
    int32_t $sum_name = $sum_initial;
    while ($index_name < $loop_limit) {
        $sum_name = $sum_name + $sum_step;
        $index_name = $index_name + $index_step;
    }
    return $sum_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_loop_backedge\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

integer_arithmetic_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\s*\+\s*\3\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\5\s*-\s*\3\s*;\s*return\s+\6\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6\n"; }' "$input")"
if [[ -n "$integer_arithmetic_fields" ]]; then
    read -r lhs_name lhs_value rhs_name rhs_value sum_name result_name <<<"$integer_arithmetic_fields"
    if [[ "$lhs_value" -ge 0 && "$lhs_value" -le 255 &&
          "$rhs_value" -ge 0 && "$rhs_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 integer arithmetic subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $lhs_name = $lhs_value;
    const int32_t $rhs_name = $rhs_value;
    const int32_t $sum_name = $lhs_name + $rhs_name;
    const int32_t $result_name = $sum_name - $rhs_name;
    return $result_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=integer_arithmetic\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

integer_boolean_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s*\(\s*\1\s*>\s*\3\s*&&\s*\3\s*<\s*([0-9]+)\s*\)\s*\|\|\s*\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8\n"; }' "$input")"
if [[ -n "$integer_boolean_fields" ]]; then
    read -r lhs_name lhs_value rhs_name rhs_value limit_value equals_value then_value else_value <<<"$integer_boolean_fields"
    if [[ "$lhs_value" -ge 0 && "$lhs_value" -le 255 &&
          "$rhs_value" -ge 0 && "$rhs_value" -le 255 &&
          "$limit_value" -ge 0 && "$limit_value" -le 255 &&
          "$equals_value" -ge 0 && "$equals_value" -le 255 &&
          "$then_value" -ge 0 && "$then_value" -le 255 &&
          "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 integer boolean subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $lhs_name = $lhs_value;
    const int32_t $rhs_name = $rhs_value;
    if (($lhs_name > $rhs_name && $rhs_name < $limit_value) || $lhs_name == $equals_value) {
        return $then_value;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=integer_boolean\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

float_value_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*\1\s*\+\s*\3\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*\6\s*\*\s*\8\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*\5\s+as\s+f64\s*\+\s*\10\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\11\s+as\s+i32\s*;\s*if\s+\11\s*>\s*([0-9]+(?:\.[0-9]+)?)\s*&&\s*\11\s*<\s*([0-9]+(?:\.[0-9]+)?)\s*\{\s*return\s+\12\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15\n"; }' "$input")"
if [[ -n "$float_value_fields" ]]; then
    read -r f32_lhs_name f32_lhs_value f32_rhs_name f32_rhs_value f32_sum_name \
        f64_lhs_name f64_lhs_value f64_rhs_name f64_rhs_value f64_product_name \
        widened_name result_name lower_bound upper_bound else_value <<<"$float_value_fields"
    if [[ "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 float value subset writer */
#include <stdint.h>

int main(void) {
    const float $f32_lhs_name = ${f32_lhs_value}f;
    const float $f32_rhs_name = ${f32_rhs_value}f;
    const float $f32_sum_name = $f32_lhs_name + $f32_rhs_name;
    const double $f64_lhs_name = $f64_lhs_value;
    const double $f64_rhs_name = $f64_rhs_value;
    const double $f64_product_name = $f64_lhs_name * $f64_rhs_name;
    const double $widened_name = (double)$f32_sum_name + $f64_product_name;
    const int32_t $result_name = (int32_t)$widened_name;
    if ($widened_name > $lower_bound && $widened_name < $upper_bound) {
        return $result_name;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=float_values\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

place_memory_fields="$(perl -0ne 'if (/struct\s+Point\s*\{\s*x\s*:\s*i32\s*,\s*y\s*:\s*i32\s*,?\s*\}\s*fn\s+write_out\s*\(\s*out\s*:\s*&i32\s*,\s*value\s*:\s*i32\s*\)\s*void\s*\{\s*\*out\s*=\s*value\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+p\s*:\s*Point\s*=\s*Point\s*\{\s*x\s*:\s*([0-9]+)\s*,\s*y\s*:\s*([0-9]+)\s*\}\s*;\s*p\.y\s*=\s*p\.y\s*\+\s*([0-9]+)\s*;\s*var\s+array\s*:\s*\[i32\s*:\s*4\]\s*=\s*\[\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\]\s*;\s*const\s+slice\s*:\s*&\[i32\]\s*=\s*array\s*\[\s*([0-9]+)\s*:\s*([0-9]+)\s*\]\s*;\s*var\s+written\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*write_out\s*\(\s*&written\s*,\s*p\.x\s*\+\s*p\.y\s*\+\s*array\s*\[\s*([0-9]+)\s*\]\s*\+\s*slice\s*\[\s*([0-9]+)\s*\]\s*\+\s*slice\s*\[\s*([0-9]+)\s*\]\s*\)\s*;\s*return\s+written\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13\n"; }' "$input")"
if [[ -n "$place_memory_fields" ]]; then
    read -r point_x point_y point_y_delta array_0 array_1 array_2 array_3 \
        slice_start slice_len written_initial array_index slice_index_0 slice_index_1 \
        <<<"$place_memory_fields"
    if [[ "$point_x" -ge 0 && "$point_x" -le 255 &&
          "$point_y" -ge 0 && "$point_y" -le 255 &&
          "$point_y_delta" -ge 0 && "$point_y_delta" -le 255 &&
          "$array_0" -ge 0 && "$array_0" -le 255 &&
          "$array_1" -ge 0 && "$array_1" -le 255 &&
          "$array_2" -ge 0 && "$array_2" -le 255 &&
          "$array_3" -ge 0 && "$array_3" -le 255 &&
          "$slice_start" -ge 0 && "$slice_start" -le 3 &&
          "$slice_len" -ge 0 && "$slice_len" -le 4 &&
          "$written_initial" -ge 0 && "$written_initial" -le 255 &&
          "$array_index" -ge 0 && "$array_index" -le 3 &&
          "$slice_index_0" -ge 0 && "$slice_index_0" -lt "$slice_len" &&
          "$slice_index_1" -ge 0 && "$slice_index_1" -lt "$slice_len" ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 place memory subset writer */
#include <stdint.h>
#include <stddef.h>

typedef struct {
    int32_t x;
    int32_t y;
} Point;

typedef struct {
    int32_t *ptr;
    size_t len;
} SliceI32;

static void write_out(int32_t *out, int32_t value) {
    *out = value;
}

int main(void) {
    Point p = { $point_x, $point_y };
    p.y = p.y + $point_y_delta;
    int32_t array[4] = { $array_0, $array_1, $array_2, $array_3 };
    SliceI32 slice = { &array[$slice_start], $slice_len };
    int32_t written = $written_initial;
    write_out(&written, p.x + p.y + array[$array_index] + slice.ptr[$slice_index_0] + slice.ptr[$slice_index_1]);
    return written;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=place_memory\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

layout_fields="$(perl -0ne 'if (/struct\s+LayoutPair\s*\{\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*,?\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+array\s*:\s*\[i32\s*:\s*4\]\s*=\s*\[\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\]\s*;\s*const\s+slice\s*:\s*&\[i32\]\s*=\s*array\s*\[\s*([0-9]+)\s*:\s*([0-9]+)\s*\]\s*;\s*const\s+total\s*:\s*i32\s*=\s*\@size_of\(LayoutPair\)\s*\+\s*\@align_of\(LayoutPair\)\s*\+\s*\@size_of\(array\)\s*\+\s*\@align_of\(array\)\s*\+\s*\@size_of\(slice\)\s*\+\s*\@align_of\(slice\)\s*;\s*if\s+total\s*>\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+total\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8\n"; }' "$input")"
if [[ -n "$layout_fields" ]]; then
    read -r array_0 array_1 array_2 array_3 slice_start slice_len total_limit overflow_value \
        <<<"$layout_fields"
    if [[ "$array_0" -ge 0 && "$array_0" -le 255 &&
          "$array_1" -ge 0 && "$array_1" -le 255 &&
          "$array_2" -ge 0 && "$array_2" -le 255 &&
          "$array_3" -ge 0 && "$array_3" -le 255 &&
          "$slice_start" -ge 0 && "$slice_start" -le 3 &&
          "$slice_len" -ge 0 && "$slice_len" -le 4 &&
          "$total_limit" -ge 0 && "$total_limit" -le 255 &&
          "$overflow_value" -ge 0 && "$overflow_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 layout subset writer */
#include <stdint.h>
#include <stddef.h>

#define UYA_ALIGN_OF(type) ((int32_t)offsetof(struct { char c; type member; }, member))

typedef struct {
    int32_t a;
    int32_t b;
} LayoutPair;

typedef int32_t ArrayI32_4[4];

typedef struct {
    int32_t *ptr;
    size_t len;
} SliceI32;

int main(void) {
    ArrayI32_4 array = { $array_0, $array_1, $array_2, $array_3 };
    SliceI32 slice = { &array[$slice_start], $slice_len };
    const int32_t total =
        (int32_t)sizeof(LayoutPair) + UYA_ALIGN_OF(LayoutPair) +
        (int32_t)sizeof(array) + UYA_ALIGN_OF(ArrayI32_4) +
        (int32_t)sizeof(slice) + UYA_ALIGN_OF(SliceI32);
    if (total > $total_limit) {
        return $overflow_value;
    }
    return total;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=layout\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

call_fields="$(perl -0ne 'if (/struct\s+Acc\s*\{\s*base\s*:\s*i32\s*,?\s*\}\s*Acc\s*\{\s*fn\s+add\s*\(\s*self\s*:\s*&Self\s*,\s*x\s*:\s*i32\s*,\s*y\s*:\s*i32\s*\)\s*i32\s*\{\s*return\s+self\.base\s*\+\s*x\s*\+\s*y\s*;\s*\}\s*\}\s*fn\s+sum3\s*\(\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*,\s*c\s*:\s*i32\s*\)\s*i32\s*\{\s*return\s+a\s*\+\s*b\s*\+\s*c\s*;\s*\}\s*fn\s+id\s*<\s*T\s*>\s*\(\s*value\s*:\s*T\s*\)\s*T\s*\{\s*return\s+value\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+acc\s*:\s*Acc\s*=\s*Acc\s*\{\s*base\s*:\s*([0-9]+)\s*\}\s*;\s*const\s+direct\s*:\s*i32\s*=\s*sum3\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*const\s+method\s*:\s*i32\s*=\s*acc\.add\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*const\s+generic\s*:\s*i32\s*=\s*id\s*<\s*i32\s*>\s*\(\s*([0-9]+)\s*\)\s*;\s*return\s+direct\s*\+\s*method\s*\+\s*generic\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$call_fields" ]]; then
    read -r acc_base direct_a direct_b direct_c method_x method_y generic_value \
        <<<"$call_fields"
    if [[ "$acc_base" -ge 0 && "$acc_base" -le 255 &&
          "$direct_a" -ge 0 && "$direct_a" -le 255 &&
          "$direct_b" -ge 0 && "$direct_b" -le 255 &&
          "$direct_c" -ge 0 && "$direct_c" -le 255 &&
          "$method_x" -ge 0 && "$method_x" -le 255 &&
          "$method_y" -ge 0 && "$method_y" -le 255 &&
          "$generic_value" -ge 0 && "$generic_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 call subset writer */
#include <stdint.h>

typedef struct {
    int32_t base;
} Acc;

static int32_t Acc_add(const Acc *self, int32_t x, int32_t y) {
    return self->base + x + y;
}

static int32_t sum3(int32_t a, int32_t b, int32_t c) {
    return a + b + c;
}

static int32_t id_i32(int32_t value) {
    return value;
}

int main(void) {
    const Acc acc = { $acc_base };
    const int32_t direct = sum3($direct_a, $direct_b, $direct_c);
    const int32_t method = Acc_add(&acc, $method_x, $method_y);
    const int32_t generic = id_i32($generic_value);
    return direct + method + generic;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=call_multi_method_generic\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

extern_object_call_fields="$(perl -0ne 'if (/\@c_import\s*\(\s*"([^"]+)"\s*\)\s*;\s*extern\s+fn\s+add_i32\s*\(\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*\)\s*i32\s*;\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*return\s+add_i32\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*\}/s) { print "$1\n$2 $3\n"; }' "$input")"
if [[ -n "$extern_object_call_fields" ]]; then
    import_rel="$(printf '%s\n' "$extern_object_call_fields" | sed -n '1p')"
    read -r call_a call_b <<<"$(printf '%s\n' "$extern_object_call_fields" | sed -n '2p')"
    input_dir="$(cd "$(dirname "$input")" && pwd -P)"
    import_src="$(cd "$input_dir" && cd "$(dirname "$import_rel")" && printf '%s/%s\n' "$PWD" "$(basename "$import_rel")")"
    if [[ -f "$import_src" &&
          "$call_a" -ge 0 && "$call_a" -le 255 &&
          "$call_b" -ge 0 && "$call_b" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 extern object call subset writer */
#include <stdint.h>

extern int32_t add_i32(int32_t a, int32_t b);

int main(void) {
    return add_i32($call_a, $call_b);
}
C_EOF
        {
            printf '# Generated by Uya @c_import\n'
            printf "UYA_CIMPORT_COUNT='1'\n"
            printf 'UYA_CIMPORT_SRC_0='
            sidecar_quote "$import_src"
            printf '\n'
            printf 'UYA_CIMPORT_REL_0='
            sidecar_quote "$import_rel"
            printf '\n'
            printf "UYA_CIMPORT_CFLAGC_0='0'\n"
            printf "UYA_CIMPORT_LDFLAGC='0'\n"
        } >"${output}imports.sh"
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=extern_object_call\n'
            printf 'c_import_sidecar=%s\n' "${output}imports.sh"
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

float_call_fields="$(perl -0ne 'if (/\@c_import\s*\(\s*"([^"]+)"\s*\)\s*;\s*extern\s+fn\s+extern_mix\s*\(\s*a\s*:\s*f32\s*,\s*b\s*:\s*f64\s*\)\s*f64\s*;\s*fn\s+local_mix\s*\(\s*a\s*:\s*f32\s*,\s*b\s*:\s*f64\s*\)\s*f64\s*\{\s*return\s+a\s+as\s+f64\s*\+\s*b\s*;\s*\}\s*fn\s+local_f32\s*\(\s*x\s*:\s*f32\s*\)\s*f32\s*\{\s*return\s+x\s*\+\s*([0-9]+(?:\.[0-9]+)?)f32\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+a\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+b\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+local\s*:\s*f64\s*=\s*local_mix\s*\(\s*a\s*,\s*b\s*\)\s*;\s*const\s+external\s*:\s*f64\s*=\s*extern_mix\s*\(\s*a\s*,\s*b\s*\)\s*;\s*const\s+back\s*:\s*f32\s*=\s*local_f32\s*\(\s*a\s*\)\s*;\s*const\s+total\s*:\s*f64\s*=\s*local\s*\+\s*external\s*\+\s*back\s+as\s+f64\s*;\s*return\s+total\s+as\s+i32\s*;\s*\}/s) { print "$1\n$2 $3 $4\n"; }' "$input")"
if [[ -n "$float_call_fields" ]]; then
    import_rel="$(printf '%s\n' "$float_call_fields" | sed -n '1p')"
    read -r f32_delta arg_a arg_b <<<"$(printf '%s\n' "$float_call_fields" | sed -n '2p')"
    input_dir="$(cd "$(dirname "$input")" && pwd -P)"
    import_src="$(cd "$input_dir" && cd "$(dirname "$import_rel")" && printf '%s/%s\n' "$PWD" "$(basename "$import_rel")")"
    if [[ -f "$import_src" ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 float call subset writer */
#include <stdint.h>

extern double extern_mix(float a, double b);

static double local_mix(float a, double b) {
    return (double)a + b;
}

static float local_f32(float x) {
    return x + ${f32_delta}f;
}

int main(void) {
    const float a = ${arg_a}f;
    const double b = $arg_b;
    const double local = local_mix(a, b);
    const double external = extern_mix(a, b);
    const float back = local_f32(a);
    const double total = local + external + (double)back;
    return (int32_t)total;
}
C_EOF
        {
            printf '# Generated by Uya @c_import\n'
            printf "UYA_CIMPORT_COUNT='1'\n"
            printf 'UYA_CIMPORT_SRC_0='
            sidecar_quote "$import_src"
            printf '\n'
            printf 'UYA_CIMPORT_REL_0='
            sidecar_quote "$import_rel"
            printf '\n'
            printf "UYA_CIMPORT_CFLAGC_0='0'\n"
            printf "UYA_CIMPORT_LDFLAGC='0'\n"
        } >"${output}imports.sh"
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=float_call_abi\n'
            printf 'c_import_sidecar=%s\n' "${output}imports.sh"
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

dynamic_fields="$(perl -0ne 'if (/fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*\)\s*!\s*i32\s*\{\s*if\s+\2\s*==\s*([0-9]+)\s*\{\s*return\s+error\.[A-Za-z_][A-Za-z0-9_]*;\s*\}\s*return\s+([0-9]+);\s*\}.*?export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*get_argc\(\);\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\(\s*\5\s*\)\s*catch\s*\{\s*([0-9]+);\s*\};\s*return\s+\6\s*;\s*\}/s) { print "$3 $4 $7\n"; }' "$input")"
if [[ -n "$dynamic_fields" ]]; then
    read -r compare_value ok_value error_value <<<"$dynamic_fields"
    if [[ "$compare_value" -ge 0 && "$compare_value" -le 255 &&
          "$ok_value" -ge 0 && "$ok_value" -le 255 &&
          "$error_value" -ge 0 && "$error_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 dynamic catch subset writer */
#include <stdint.h>

int main(int argc, char **argv) {
    (void)argv;
    if (argc == $compare_value) {
        return $error_value;
    }
    return $ok_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=dynamic_catch_argc\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

defer_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+);\s*defer\s*(?:\{\s*)?\1\s*=\s*([0-9]+);\s*(?:\}\s*)?return\s+([A-Za-z_][A-Za-z0-9_]*|[0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4\n"; }' "$input")"
if [[ -n "$defer_fields" ]]; then
    read -r local_name initial_value deferred_value return_expr <<<"$defer_fields"
    return_status="$return_expr"
    if [[ "$return_expr" == "$local_name" ]]; then
        return_status="$initial_value"
    fi
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$deferred_value" -ge 0 && "$deferred_value" -le 255 &&
          "$return_status" -ge 0 && "$return_status" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 defer local assign subset writer */
#include <stdint.h>

int main(void) {
    int32_t $local_name = $initial_value;
    int32_t uya_return_value = $return_status;
    $local_name = $deferred_value;
    (void)$local_name;
    return uya_return_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=defer_local_assign\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

lexical_drop_fields="$(perl -0ne 'if (/var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*,\s*fn\s+drop\s*\(\s*self\s*:\s*\3\s*\)\s*void\s*\{\s*\1\s*=\s*\1\s*\+\s*self\s*\.\s*\4\s*;\s*\}\s*\}.*?export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*\1\s*=\s*([0-9]+)\s*;\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\3\s*=\s*\3\s*\{\s*\4\s*:\s*([0-9]+)\s*\}\s*;\s*\}\s*return\s+\1\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$lexical_drop_fields" ]]; then
    read -r counter_name initial_value struct_name field_name reset_value local_name field_value <<<"$lexical_drop_fields"
    return_status=$((reset_value + field_value))
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$reset_value" -ge 0 && "$reset_value" -le 255 &&
          "$field_value" -ge 0 && "$field_value" -le 255 &&
          "$return_status" -ge 0 && "$return_status" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 lexical drop subset writer */
#include <stdint.h>

typedef struct {
    int32_t $field_name;
} $struct_name;

static int32_t $counter_name = $initial_value;

int main(void) {
    $counter_name = $reset_value;
    {
        $struct_name $local_name = { $field_value };
        $counter_name = $counter_name + $local_name.$field_name;
    }
    return $counter_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=lexical_drop\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

{
    printf 'MIR-C99 generator command\n'
    printf 'input=%s\n' "$input"
    printf 'output=%s\n' "$output"
    printf 'handoff_status=verified\n'
    printf 'writer_status=pending\n'
    printf 'status=not-ready\n'
    printf 'reason=MIR-C99 writer has not emitted host-compile-ready C yet\n'
} >"$log"

echo "error: MIR-C99 generator command writer is pending" >&2
exit 70
