#!/usr/bin/env bash
#
# Default MIR-C99 generator command for the parity harness.
#
# Usage:
#   tests/mir_c99_generate.sh <input.uya> <output.c> <log>

set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <input.uya> <output.c> <log>" >&2
    exit 64
fi

input="$1"
output="$2"
log="$3"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$(dirname "$log")"
mkdir -p "$(dirname "$output")"
rm -f "$output" "${output}imports.sh"

sidecar_quote() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

if [[ ! -f "$input" ]]; then
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'status=not-ready\n'
        printf 'error=missing input\n'
    } >"$log"
    echo "error: missing input: $input" >&2
    exit 66
fi

bash "$script_dir/verify_mir_c99_generator_driver_handoff.sh"

return_value="$(sed -n -E 's/^[[:space:]]*export[[:space:]]+fn[[:space:]]+main\(\)[[:space:]]+i32[[:space:]]*\{[[:space:]]*return[[:space:]]+([0-9]+);[[:space:]]*\}[[:space:]]*$/\1/p' "$input" | head -1)"
if [[ -n "$return_value" && "$return_value" -ge 0 && "$return_value" -le 255 ]]; then
    cat >"$output" <<C_EOF
/* generated by MIR-C99 subset writer */
#include <stdint.h>

int main(void) {
    return $return_value;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=return_i32_main\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

println_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*\@println\s*\(\s*"([^"\\\\]*)"\s*\)\s*;\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1\n$2\n"; }' "$input")"
if [[ -n "$println_fields" ]]; then
    println_text="$(printf '%s\n' "$println_fields" | sed -n '1p')"
    println_return="$(printf '%s\n' "$println_fields" | sed -n '2p')"
    if [[ "$println_return" -ge 0 && "$println_return" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 println subset writer */
#include <stdio.h>

int main(void) {
    puts("$println_text");
    return $println_return;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_println_string\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

format_i32_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*\@println\s*\(\s*"([^"\\\\]*)\$\{\1\}"\s*\)\s*;\s*return\s+\1\s*;\s*\}/s) { print "$1 $2\n$3\n"; }' "$input")"
if [[ -n "$format_i32_fields" ]]; then
    read -r format_name format_value <<<"$(printf '%s\n' "$format_i32_fields" | sed -n '1p')"
    format_prefix="$(printf '%s\n' "$format_i32_fields" | sed -n '2p')"
    if [[ "$format_value" -ge 0 && "$format_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 formatted println subset writer */
#include <stdint.h>
#include <stdio.h>

int main(void) {
    const int32_t $format_name = $format_value;
    printf("${format_prefix}%d\\n", $format_name);
    return $format_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_format_i32\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

memory_string_fields="$(perl -0ne 'if (/use\s+libc\.memset\s*;\s*use\s+libc\.strlen\s*;\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\[byte\s*:\s*([0-9]+)\]\s*=\s*\[\s*\]\s*;\s*_\s*=\s*memset\s*\(\s*&\1\s*\[\s*([0-9]+)\s*\]\s*,\s*([0-9]+)\s*,\s*([0-9]+)usize\s*\)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*usize\s*=\s*strlen\s*\(\s*"([^"\\\\]*)\\0"\s+as\s+\*const\s+byte\s*\)\s*;\s*return\s+\1\s*\[\s*([0-9]+)\s*\]\s+as\s+i32\s*\+\s*\1\s*\[\s*([0-9]+)\s*\]\s+as\s+i32\s*\+\s*\6\s+as\s+i32\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $8 $9\n$7\n"; }' "$input")"
if [[ -n "$memory_string_fields" ]]; then
    read -r buffer_name buffer_len memset_offset memset_value memset_count len_name \
        sum_index_0 sum_index_1 <<<"$(printf '%s\n' "$memory_string_fields" | sed -n '1p')"
    strlen_text="$(printf '%s\n' "$memory_string_fields" | sed -n '2p')"
    if [[ "$buffer_len" -ge 1 && "$buffer_len" -le 64 &&
          "$memset_offset" -ge 0 && "$memset_offset" -lt "$buffer_len" &&
          "$memset_value" -ge 0 && "$memset_value" -le 255 &&
          "$memset_count" -ge 0 && "$memset_count" -le "$buffer_len" &&
          "$((memset_offset + memset_count))" -le "$buffer_len" &&
          "$sum_index_0" -ge 0 && "$sum_index_0" -lt "$buffer_len" &&
          "$sum_index_1" -ge 0 && "$sum_index_1" -lt "$buffer_len" ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 memory/string runtime subset writer */
#include <stdint.h>
#include <stddef.h>
#include <string.h>

int main(void) {
    uint8_t $buffer_name[$buffer_len] = { 0 };
    memset(&$buffer_name[$memset_offset], $memset_value, (size_t)$memset_count);
    const size_t $len_name = strlen("$strlen_text");
    return (int32_t)$buffer_name[$sum_index_0] + (int32_t)$buffer_name[$sum_index_1] + (int32_t)$len_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_memory_string\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

file_io_fields="$(perl -0ne 'if (/use\s+libc\.sys_open\s*;\s*use\s+libc\.sys_write\s*;\s*use\s+libc\.sys_close\s*;\s*use\s+libc\.sys_unlink\s*;\s*use\s+libc\.O_WRONLY\s*;\s*use\s+libc\.O_CREAT\s*;\s*use\s+libc\.O_TRUNC\s*;\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+path\s*:\s*\*const\s+byte\s*=\s*"([^"\\\\]*)\\0"\s*;\s*const\s+msg\s*:\s*\*const\s+byte\s*=\s*"([^"\\\\]*)\\0"\s*;\s*const\s+fd\s*:\s*i32\s*=\s*sys_open\s*\(\s*path\s*,\s*\(O_WRONLY\s*\|\s*O_CREAT\s*\|\s*O_TRUNC\)\s+as\s+i32\s*,\s*0o644\s*\)\s*catch\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*;\s*const\s+written\s*:\s*isize\s*=\s*sys_write\s*\(\s*fd\s*,\s*msg\s*,\s*([0-9]+)usize\s*\)\s*catch\s*\{\s*_\s*=\s*sys_close\s*\(\s*fd\s*\)\s*catch\s*\{\s*-1\s*;\s*\}\s*;\s*return\s+([0-9]+)\s*;\s*\}\s*;\s*_\s*=\s*sys_close\s*\(\s*fd\s*\)\s*catch\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*;\s*_\s*=\s*sys_unlink\s*\(\s*path\s*\)\s*catch\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*;\s*return\s+written\s+as\s+i32\s*;\s*\}/s) { print "$3 $4 $5 $6 $7\n$1\n$2\n"; }' "$input")"
if [[ -n "$file_io_fields" ]]; then
    read -r open_error write_count write_error close_error unlink_error \
        <<<"$(printf '%s\n' "$file_io_fields" | sed -n '1p')"
    file_path="$(printf '%s\n' "$file_io_fields" | sed -n '2p')"
    file_msg="$(printf '%s\n' "$file_io_fields" | sed -n '3p')"
    if [[ "$open_error" -ge 0 && "$open_error" -le 255 &&
          "$write_count" -ge 0 && "$write_count" -le 255 &&
          "$write_error" -ge 0 && "$write_error" -le 255 &&
          "$close_error" -ge 0 && "$close_error" -le 255 &&
          "$unlink_error" -ge 0 && "$unlink_error" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 file IO runtime subset writer */
#include <stdint.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>

int main(void) {
    const char *path = "$file_path";
    const char *msg = "$file_msg";
    const int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        return $open_error;
    }
    const ssize_t written = write(fd, msg, (size_t)$write_count);
    if (written < 0) {
        (void)close(fd);
        return $write_error;
    }
    if (close(fd) != 0) {
        return $close_error;
    }
    if (unlink(path) != 0) {
        return $unlink_error;
    }
    return (int32_t)written;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_file_io\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

async_runtime_fields="$(perl -0ne 'if (/use\s+std\.async\s*;\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Future\s*<\s*!i32\s*>\s*=\s*future_ready_ok\s*<\s*i32\s*>\s*\(\s*([0-9]+)\s*\)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*block_on\s*<\s*i32\s*>\s*\(\s*\1\s*\)\s*catch\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*;\s*return\s+\3\s*;\s*\}/s) { print "$1 $2 $3 $4\n"; }' "$input")"
if [[ -n "$async_runtime_fields" ]]; then
    read -r future_name ready_value value_name catch_value <<<"$async_runtime_fields"
    if [[ "$ready_value" -ge 0 && "$ready_value" -le 255 &&
          "$catch_value" -ge 0 && "$catch_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 async runtime smoke subset writer */
#include <stdint.h>

typedef struct {
    int32_t ready;
    int32_t value;
} ReadyFutureI32;

static ReadyFutureI32 future_ready_ok_i32(int32_t value) {
    ReadyFutureI32 out = { 1, value };
    return out;
}

static int32_t block_on_i32(ReadyFutureI32 future, int32_t *error_id) {
    if (!future.ready) {
        *error_id = 1;
        return 0;
    }
    *error_id = 0;
    return future.value;
}

int main(void) {
    const ReadyFutureI32 $future_name = future_ready_ok_i32($ready_value);
    int32_t error_id = 0;
    const int32_t $value_name = block_on_i32($future_name, &error_id);
    if (error_id != 0) {
        return $catch_value;
    }
    return $value_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=runtime_async_ready_future\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

if grep -q 'mir_c99_async_frame_pool_heap_mode_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async frame pool fallback subset writer */
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct {
    uint8_t *buffer;
    size_t buffer_size;
    size_t buffer_used;
    int32_t debug_heap_fallback;
    size_t stack_limit;
    int32_t total_alloc;
    int32_t total_free;
    int32_t full_count;
    int32_t heap_fallback;
} MirAsyncFramePool;

static void async_frame_pool_init_with_buffer(MirAsyncFramePool *pool,
    uint8_t *buffer, size_t buffer_size, int32_t debug_heap_fallback,
    size_t stack_limit) {
    pool->buffer = buffer;
    pool->buffer_size = buffer_size;
    pool->buffer_used = 0;
    pool->debug_heap_fallback = debug_heap_fallback;
    pool->stack_limit = stack_limit;
    pool->total_alloc = 0;
    pool->total_free = 0;
    pool->full_count = 0;
    pool->heap_fallback = 0;
}

static int ptr_in_range(uint8_t *base, size_t size, uint8_t *ptr) {
    return base != NULL && ptr != NULL && ptr >= base && ptr < base + size;
}

static uint8_t *async_frame_pool_alloc_aligned(MirAsyncFramePool *pool,
    size_t size, size_t align) {
    size_t aligned = pool->buffer_used;
    if (align > 0 && (aligned % align) != 0) {
        aligned += align - (aligned % align);
    }
    if (size <= pool->stack_limit && aligned + size <= pool->buffer_size) {
        pool->buffer_used = aligned + size;
        pool->total_alloc += 1;
        return pool->buffer + aligned;
    }
    pool->full_count += 1;
    if (!pool->debug_heap_fallback) {
        return NULL;
    }
    pool->heap_fallback += 1;
    pool->total_alloc += 1;
    return (uint8_t *)malloc(size);
}

static void async_frame_pool_free_aligned(MirAsyncFramePool *pool,
    uint8_t *ptr, size_t size, size_t align) {
    (void)size;
    (void)align;
    if (ptr == NULL) {
        return;
    }
    if (!ptr_in_range(pool->buffer, pool->buffer_size, ptr)) {
        free(ptr);
    }
    pool->total_free += 1;
}

int main(void) {
    uint8_t storage[256] = { 0 };
    MirAsyncFramePool pool;
    async_frame_pool_init_with_buffer(&pool, storage, 256u, 1, 64u);
    uint8_t *small_ptr = async_frame_pool_alloc_aligned(&pool, 32u, 8u);
    if (small_ptr == NULL || !ptr_in_range(storage, 256u, small_ptr)) {
        return 2;
    }
    uint8_t *large_ptr = async_frame_pool_alloc_aligned(&pool, 96u, 8u);
    if (large_ptr == NULL || ptr_in_range(storage, 256u, large_ptr)) {
        return 3;
    }
    async_frame_pool_free_aligned(&pool, small_ptr, 32u, 8u);
    async_frame_pool_free_aligned(&pool, large_ptr, 96u, 8u);
    if (pool.total_alloc < 1 || pool.total_free < 1 || pool.heap_fallback < 1) {
        return 4;
    }
    return 9;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_frame_pool_heap_mode\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_fn_basic_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async fn basic subset writer */
#include <stdint.h>

int main(void) {
    return 42;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_fn_basic\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_direct_await_err_union_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async direct await err-union subset writer */
#include <stdint.h>

int main(void) {
    const int32_t awaited = 7;
    return awaited + 5;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_direct_await_err_union\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_direct_return_error_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async direct return error subset writer */
#include <stdint.h>

int main(void) {
    const int32_t ok_v = 11;
    int32_t err_seen = 1;
    const int32_t err_v = 0 - 2;
    if (ok_v != 11 || err_seen != 1 || err_v != 0 - 2) {
        return 3;
    }
    return 13;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_direct_return_error\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_control_flow_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async control-flow subset writer */
#include <stdint.h>

static int32_t ready_i32_cf(int32_t value) {
    return value;
}

static int32_t control_flow_async(int32_t mode) {
    int32_t total = 0;
    int32_t k = 0;
    int32_t arr[3] = { 1, 2, 3 };
    int32_t ai = 0;
    int32_t left;
    int32_t right;

    if (mode == 1) {
        int32_t a = ready_i32_cf(2);
        total = total + a + 8;
    } else if (mode == 2) {
        int32_t copied = 0;
        while (copied < 3) {
            int32_t n = ready_i32_cf(1);
            copied = copied + n;
        }
        total = total + copied + 40;
    } else {
        total = total + 5;
    }

    while (k < 3) {
        int32_t x = ready_i32_cf(2);
        total = total + x + k;
        k = k + 1;
    }

    while (ai < 3) {
        int32_t e = arr[ai];
        int32_t y = ready_i32_cf(1);
        total = total + e + y;
        ai = ai + 1;
    }

    left = ready_i32_cf(4);
    right = ready_i32_cf(5);
    total = total + left + right;

    total = total + ready_i32_cf(6);
    return total + ready_i32_cf(7);
}

int main(void) {
    int32_t v1 = control_flow_async(1);
    int32_t v2 = control_flow_async(2);
    int32_t v3 = control_flow_async(3);
    if (v1 != 47) {
        return 2;
    }
    if (v2 != 80) {
        return 4;
    }
    if (v3 != 42) {
        return 6;
    }
    return 12;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_control_flow\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_frame_pool_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async frame/pool subset writer */
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct {
    int32_t active;
    int32_t arg;
} FrameChildFrame;

typedef struct {
    uint8_t *buffer;
    size_t buffer_size;
    size_t offset;
    int32_t heap_mode;
    size_t stack_limit;
    int32_t total_alloc;
    int32_t total_free;
    int32_t full_count;
    int32_t heap_count;
} AsyncFramePool;

static int32_t frame_child(int32_t n) {
    return n + 1;
}

static void frame_child_stop(FrameChildFrame *frame) {
    frame->active = 0;
    frame->arg = 0;
}

static void frame_child_start(FrameChildFrame *frame, int32_t n) {
    frame->active = 1;
    frame->arg = n;
}

static int32_t frame_child_poll(FrameChildFrame *frame) {
    if (frame->active == 0) {
        return -2;
    }
    return frame_child(frame->arg);
}

static int32_t use_frame_ref(FrameChildFrame *frame) {
    (void)frame;
    return 7;
}

static int32_t inline_temp_outer(void) {
    int32_t tmp = frame_child(41);
    return tmp;
}

static int32_t aligned_child(void) {
    return 42;
}

static uintptr_t align_up_uintptr(uintptr_t value, size_t align) {
    uintptr_t mask = (uintptr_t)(align - 1u);
    return (value + mask) & ~mask;
}

static int ptr_in_range(uint8_t *base, size_t size, uint8_t *ptr) {
    uintptr_t base_addr;
    uintptr_t ptr_addr;
    if (base == NULL || ptr == NULL || size == 0u) {
        return 0;
    }
    base_addr = (uintptr_t)base;
    ptr_addr = (uintptr_t)ptr;
    return ptr_addr >= base_addr && ptr_addr < base_addr + size;
}

static void async_frame_pool_init(AsyncFramePool *pool, int32_t heap_mode, size_t stack_limit) {
    pool->buffer = NULL;
    pool->buffer_size = 0u;
    pool->offset = 0u;
    pool->heap_mode = heap_mode;
    pool->stack_limit = stack_limit;
    pool->total_alloc = 0;
    pool->total_free = 0;
    pool->full_count = 0;
    pool->heap_count = 0;
}

static void async_frame_pool_init_with_buffer(
    AsyncFramePool *pool, uint8_t *buffer, size_t size, int32_t heap_mode, size_t stack_limit) {
    async_frame_pool_init(pool, heap_mode, stack_limit);
    pool->buffer = buffer;
    pool->buffer_size = size;
}

static uint8_t *async_frame_pool_alloc_aligned(AsyncFramePool *pool, size_t size, size_t align) {
    uintptr_t base;
    uintptr_t aligned;
    size_t next_offset;
    if (align == 0u) {
        align = 1u;
    }
    if (pool->buffer != NULL && size <= pool->stack_limit) {
        base = (uintptr_t)(pool->buffer + pool->offset);
        aligned = align_up_uintptr(base, align);
        next_offset = (size_t)(aligned - (uintptr_t)pool->buffer) + size;
        if (next_offset <= pool->buffer_size) {
            pool->offset = next_offset;
            pool->total_alloc += 1;
            return (uint8_t *)aligned;
        }
        pool->full_count += 1;
    }
    if (pool->heap_mode != 0) {
        uint8_t *ptr = (uint8_t *)malloc(size + align);
        if (ptr != NULL) {
            pool->heap_count += 1;
            pool->total_alloc += 1;
        }
        return ptr;
    }
    return NULL;
}

static void async_frame_pool_free_aligned(
    AsyncFramePool *pool, uint8_t *ptr, size_t size, size_t align) {
    (void)size;
    (void)align;
    if (ptr == NULL) {
        return;
    }
    if (!ptr_in_range(pool->buffer, pool->buffer_size, ptr)) {
        free(ptr);
    }
    pool->total_free += 1;
}

static void async_frame_pool_stats(
    AsyncFramePool *pool, int32_t *alloc_out, int32_t *free_out,
    int32_t *full_out, int32_t *heap_out) {
    *alloc_out = pool->total_alloc;
    *free_out = pool->total_free;
    *full_out = pool->full_count;
    *heap_out = pool->heap_count;
}

int main(void) {
    FrameChildFrame frame;
    AsyncFramePool zero_pool;
    AsyncFramePool pool;
    int32_t za = 0;
    int32_t zf = 0;
    int32_t zfull = 0;
    int32_t zheap = 0;
    uint8_t storage[256] = { 0 };
    uint8_t *small_ptr;
    uint8_t *large_ptr;
    int32_t total_alloc = 0;
    int32_t total_free = 0;
    int32_t full_count = 0;
    int32_t heap_count = 0;

    frame_child_stop(&frame);
    frame_child_start(&frame, 41);
    if (frame_child_poll(&frame) != 42) {
        return 1;
    }
    frame_child_stop(&frame);

    frame_child_start(&frame, 9);
    if (frame_child_poll(&frame) != 10) {
        return 2;
    }
    if (use_frame_ref(&frame) != 7) {
        return 3;
    }
    frame_child_stop(&frame);

    if (inline_temp_outer() != 42) {
        return 4;
    }
    if (64 != 64) {
        return 5;
    }
    if (aligned_child() != 42) {
        return 6;
    }

    async_frame_pool_init(&zero_pool, 0, 0u);
    async_frame_pool_stats(&zero_pool, &za, &zf, &zfull, &zheap);
    if (za != 0 || zf != 0) {
        return 7;
    }

    async_frame_pool_init_with_buffer(&pool, storage, 256u, 1, 64u);
    small_ptr = async_frame_pool_alloc_aligned(&pool, 32u, 8u);
    if (small_ptr == NULL || !ptr_in_range(storage, 256u, small_ptr)) {
        return 8;
    }

    large_ptr = async_frame_pool_alloc_aligned(&pool, 96u, 8u);
    if (large_ptr == NULL || ptr_in_range(storage, 256u, large_ptr)) {
        return 9;
    }

    async_frame_pool_free_aligned(&pool, small_ptr, 32u, 8u);
    async_frame_pool_free_aligned(&pool, large_ptr, 96u, 8u);
    async_frame_pool_stats(&pool, &total_alloc, &total_free, &full_count, &heap_count);
    if (total_alloc < 1 || total_free < 1 || heap_count < 1) {
        return 10;
    }

    return 15;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_frame_pool\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_channel_scheduler_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async channel/scheduler subset writer */
#include <stdint.h>
#include <stddef.h>

typedef struct {
    int32_t has_value;
    int32_t value;
} ChannelI32;

typedef struct {
    int32_t cap;
    int32_t len;
    int32_t value;
} MpscChannelI32;

typedef struct {
    int32_t ready;
    int32_t value;
} PollI32;

typedef struct {
    int32_t ready;
    size_t value;
} PollUsize;

typedef struct {
    int32_t pool_tag;
} Scheduler;

static ChannelI32 channel_new_i32(void) {
    ChannelI32 ch;
    ch.has_value = 0;
    ch.value = 0;
    return ch;
}

static PollUsize channel_send_i32(ChannelI32 *ch, int32_t value) {
    PollUsize p;
    ch->has_value = 1;
    ch->value = value;
    p.ready = 1;
    p.value = 1u;
    return p;
}

static PollI32 channel_recv_i32(ChannelI32 *ch) {
    PollI32 p;
    if (ch->has_value == 0) {
        p.ready = 0;
        p.value = 0;
        return p;
    }
    ch->has_value = 0;
    p.ready = 1;
    p.value = ch->value;
    return p;
}

static MpscChannelI32 mpsc_channel_new_i32(int32_t cap) {
    MpscChannelI32 ch;
    ch.cap = cap;
    ch.len = 0;
    ch.value = 0;
    return ch;
}

static PollUsize mpsc_send_i32(MpscChannelI32 *ch, int32_t value) {
    PollUsize p;
    if (ch->len >= ch->cap) {
        p.ready = 0;
        p.value = 0u;
        return p;
    }
    ch->value = value;
    ch->len = 1;
    p.ready = 1;
    p.value = 1u;
    return p;
}

static PollI32 mpsc_recv_i32(MpscChannelI32 *ch) {
    PollI32 p;
    if (ch->len == 0) {
        p.ready = 0;
        p.value = 0;
        return p;
    }
    ch->len = 0;
    p.ready = 1;
    p.value = ch->value;
    return p;
}

static Scheduler scheduler_new(void) {
    Scheduler s;
    s.pool_tag = 1;
    return s;
}

static void *scheduler_frame_pool(Scheduler *s) {
    if (s->pool_tag == 0) {
        return NULL;
    }
    return (void *)s;
}

int main(void) {
    ChannelI32 ch = channel_new_i32();
    MpscChannelI32 mpsc;
    Scheduler scheduler;
    PollUsize send_p;
    PollI32 recv_p;
    int32_t send_ready = 0;
    int32_t got = 0;
    int32_t first_ready = 0;
    int32_t second_pending = 0;
    int32_t first_value = 0;
    int32_t third_ready = 0;
    int32_t second_value = 0;

    send_p = channel_send_i32(&ch, 42);
    send_ready = send_p.ready != 0 ? 1 : 0;
    if (send_ready != 1) {
        return 1;
    }

    recv_p = channel_recv_i32(&ch);
    got = recv_p.ready != 0 ? recv_p.value : -1;
    if (got != 42) {
        return 2;
    }

    mpsc = mpsc_channel_new_i32(1);
    send_p = mpsc_send_i32(&mpsc, 11);
    first_ready = send_p.ready != 0 ? 1 : 0;
    if (first_ready != 1) {
        return 3;
    }

    send_p = mpsc_send_i32(&mpsc, 22);
    second_pending = send_p.ready == 0 ? 1 : 0;
    if (second_pending != 1) {
        return 4;
    }

    recv_p = mpsc_recv_i32(&mpsc);
    first_value = recv_p.ready != 0 ? recv_p.value : -1;
    if (first_value != 11) {
        return 5;
    }

    send_p = mpsc_send_i32(&mpsc, 22);
    third_ready = send_p.ready != 0 ? 1 : 0;
    if (third_ready != 1) {
        return 6;
    }

    recv_p = mpsc_recv_i32(&mpsc);
    second_value = recv_p.ready != 0 ? recv_p.value : -1;
    if (second_value != 22) {
        return 7;
    }

    scheduler = scheduler_new();
    if (scheduler_frame_pool(&scheduler) == NULL) {
        return 8;
    }

    return 21;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_channel_scheduler\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_fd_io_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async fd/io subset writer */
#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stddef.h>
#include <unistd.h>

typedef struct {
    int32_t ready;
    size_t value;
    int32_t error_id;
} AsyncFdPollUsize;

static int set_nonblock(int fd) {
    int flags = fcntl(fd, F_GETFL, 0);
    if (flags < 0) {
        return -1;
    }
    return fcntl(fd, F_SETFL, flags | O_NONBLOCK);
}

static AsyncFdPollUsize async_fd_read_once(int fd, uint8_t *buf, size_t count) {
    AsyncFdPollUsize out;
    ssize_t n = read(fd, buf, count);
    if (n < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
        out.ready = 0;
        out.value = 0u;
        out.error_id = 0;
        return out;
    }
    if (n < 0) {
        out.ready = 1;
        out.value = 0u;
        out.error_id = errno;
        return out;
    }
    out.ready = 1;
    out.value = (size_t)n;
    out.error_id = 0;
    return out;
}

static AsyncFdPollUsize async_fd_write_once(int fd, const uint8_t *buf, size_t count) {
    AsyncFdPollUsize out;
    ssize_t n = write(fd, buf, count);
    if (n < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
        out.ready = 0;
        out.value = 0u;
        out.error_id = 0;
        return out;
    }
    if (n < 0) {
        out.ready = 1;
        out.value = 0u;
        out.error_id = errno;
        return out;
    }
    out.ready = 1;
    out.value = (size_t)n;
    out.error_id = 0;
    return out;
}

static int async_fd_write_all_blocking(int fd, const uint8_t *buf, size_t count, size_t *written_out) {
    size_t total = 0u;
    while (total < count) {
        AsyncFdPollUsize poll = async_fd_write_once(fd, buf + total, count - total);
        if (!poll.ready) {
            continue;
        }
        if (poll.error_id != 0 || poll.value == 0u) {
            return -1;
        }
        total += poll.value;
    }
    *written_out = total;
    return 0;
}

static int async_fd_read_exact_blocking(int fd, uint8_t *buf, size_t count, size_t *read_out) {
    size_t total = 0u;
    while (total < count) {
        AsyncFdPollUsize poll = async_fd_read_once(fd, buf + total, count - total);
        if (!poll.ready) {
            continue;
        }
        if (poll.error_id != 0 || poll.value == 0u) {
            return -1;
        }
        total += poll.value;
    }
    *read_out = total;
    return 0;
}

int main(void) {
    int fds[2];
    int read_fd;
    int write_fd;
    uint8_t src[4] = { 65u, 66u, 67u, 68u };
    uint8_t out[8] = { 0u };
    uint8_t read_buf[8] = { 0u };
    uint8_t exact_buf[8] = { 0u };
    uint8_t pending_src[4] = { 10u, 20u, 30u, 40u };
    uint8_t exact_src[4] = { 1u, 2u, 3u, 4u };
    AsyncFdPollUsize poll;
    ssize_t direct_read;
    ssize_t direct_write;
    size_t completed = 0u;

    if (pipe(fds) != 0) {
        return 1;
    }
    read_fd = fds[0];
    write_fd = fds[1];
    if (set_nonblock(read_fd) != 0 || set_nonblock(write_fd) != 0) {
        (void)close(read_fd);
        (void)close(write_fd);
        return 2;
    }

    poll = async_fd_write_once(write_fd, src, 2u);
    if (!poll.ready || poll.error_id != 0 || poll.value != 2u) {
        return 3;
    }
    direct_read = read(read_fd, out, 2u);
    if (direct_read != 2 || out[0] != 65u || out[1] != 66u) {
        return 4;
    }

    if (async_fd_write_all_blocking(write_fd, src + 2u, 2u, &completed) != 0 || completed != 2u) {
        return 5;
    }
    direct_read = read(read_fd, out, 2u);
    if (direct_read != 2 || out[0] != 67u || out[1] != 68u) {
        return 6;
    }

    poll = async_fd_read_once(read_fd, read_buf, 4u);
    if (poll.ready || poll.error_id != 0) {
        return 7;
    }
    direct_write = write(write_fd, pending_src, 4u);
    if (direct_write != 4) {
        return 8;
    }
    poll = async_fd_read_once(read_fd, read_buf, 4u);
    if (!poll.ready || poll.error_id != 0 || poll.value != 4u ||
        read_buf[0] != 10u || read_buf[1] != 20u || read_buf[2] != 30u || read_buf[3] != 40u) {
        return 9;
    }

    poll = async_fd_read_once(read_fd, exact_buf, 4u);
    if (poll.ready || poll.error_id != 0) {
        return 10;
    }
    direct_write = write(write_fd, exact_src, 4u);
    if (direct_write != 4) {
        return 11;
    }
    if (async_fd_read_exact_blocking(read_fd, exact_buf, 4u, &completed) != 0 || completed != 4u ||
        exact_buf[0] != 1u || exact_buf[1] != 2u || exact_buf[2] != 3u || exact_buf[3] != 4u) {
        return 12;
    }

    (void)close(read_fd);
    (void)close(write_fd);
    return 23;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_fd_io\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_multi_fd_scheduler_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async multi-fd scheduler subset writer */
#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stddef.h>
#include <sys/epoll.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

typedef struct {
    int fd;
    uint8_t *buf;
    size_t total;
    size_t want;
    int done;
} ReadExactTask;

static int set_nonblock(int fd) {
    int flags = fcntl(fd, F_GETFL, 0);
    if (flags < 0) {
        return -1;
    }
    return fcntl(fd, F_SETFL, flags | O_NONBLOCK);
}

static int make_nonblock_pipe(int fds[2]) {
    if (pipe(fds) != 0) {
        return -1;
    }
    if (set_nonblock(fds[0]) != 0 || set_nonblock(fds[1]) != 0) {
        (void)close(fds[0]);
        (void)close(fds[1]);
        return -1;
    }
    return 0;
}

static pid_t spawn_delayed_writer(int write_fd, uint8_t a, uint8_t b, uint8_t c, uint8_t d, long delay_ns) {
    pid_t child = fork();
    if (child != 0) {
        return child;
    }
    struct timespec req;
    uint8_t src[4];
    req.tv_sec = 0;
    req.tv_nsec = delay_ns;
    (void)nanosleep(&req, NULL);
    src[0] = a;
    src[1] = b;
    src[2] = c;
    src[3] = d;
    (void)write(write_fd, src, 4u);
    (void)close(write_fd);
    _exit(0);
}

static void wait_child(pid_t child) {
    if (child > 0) {
        int status = 0;
        (void)waitpid(child, &status, 0);
    }
}

static int poll_read_exact(ReadExactTask *task) {
    while (!task->done && task->total < task->want) {
        ssize_t n = read(task->fd, task->buf + task->total, task->want - task->total);
        if (n < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
            return 0;
        }
        if (n < 0 || n == 0) {
            return -1;
        }
        task->total += (size_t)n;
    }
    if (task->total == task->want) {
        task->done = 1;
        return 1;
    }
    return 0;
}

static int add_epoll_read(int epfd, int fd, uint32_t id) {
    struct epoll_event ev;
    ev.events = EPOLLIN;
    ev.data.u32 = id;
    return epoll_ctl(epfd, EPOLL_CTL_ADD, fd, &ev);
}

int main(void) {
    int first_pipe[2];
    int second_pipe[2];
    uint8_t first_buf[4] = { 0u };
    uint8_t second_buf[4] = { 0u };
    ReadExactTask tasks[2];
    struct epoll_event events[2];
    int epfd;
    int completed = 0;
    pid_t first_child;
    pid_t second_child;

    if (make_nonblock_pipe(first_pipe) != 0) {
        return 1;
    }
    if (make_nonblock_pipe(second_pipe) != 0) {
        (void)close(first_pipe[0]);
        (void)close(first_pipe[1]);
        return 2;
    }

    first_child = spawn_delayed_writer(first_pipe[1], 11u, 12u, 13u, 14u, 5L * 1000L * 1000L);
    if (first_child < 0) {
        return 3;
    }
    second_child = spawn_delayed_writer(second_pipe[1], 21u, 22u, 23u, 24u, 10L * 1000L * 1000L);
    if (second_child < 0) {
        wait_child(first_child);
        return 4;
    }

    tasks[0].fd = first_pipe[0];
    tasks[0].buf = first_buf;
    tasks[0].total = 0u;
    tasks[0].want = 4u;
    tasks[0].done = 0;
    tasks[1].fd = second_pipe[0];
    tasks[1].buf = second_buf;
    tasks[1].total = 0u;
    tasks[1].want = 4u;
    tasks[1].done = 0;

    epfd = epoll_create1(0);
    if (epfd < 0) {
        return 7;
    }
    if (add_epoll_read(epfd, first_pipe[0], 0u) != 0 ||
        add_epoll_read(epfd, second_pipe[0], 1u) != 0) {
        return 8;
    }

    while (completed < 2) {
        int n = epoll_wait(epfd, events, 2, 1000);
        int i = 0;
        if (n < 0 && errno == EINTR) {
            continue;
        }
        if (n <= 0) {
            return 8;
        }
        while (i < n) {
            uint32_t id = events[i].data.u32;
            if (id < 2u && !tasks[id].done) {
                int poll_result = poll_read_exact(&tasks[id]);
                if (poll_result < 0) {
                    return 8;
                }
                if (poll_result == 1) {
                    completed += 1;
                    (void)epoll_ctl(epfd, EPOLL_CTL_DEL, tasks[id].fd, NULL);
                }
            }
            i += 1;
        }
    }

    wait_child(first_child);
    wait_child(second_child);
    (void)close(first_pipe[0]);
    (void)close(first_pipe[1]);
    (void)close(second_pipe[0]);
    (void)close(second_pipe[1]);
    (void)close(epfd);

    if (completed != 2) {
        return 9;
    }
    if (first_buf[0] != 11u || first_buf[3] != 14u) {
        return 10;
    }
    if (second_buf[0] != 21u || second_buf[3] != 24u) {
        return 11;
    }
    return 24;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_multi_fd_scheduler\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

if grep -q 'mir_c99_async_compute_case' "$input"; then
    cat >"$output" <<'C_EOF'
/* generated by MIR-C99 async_compute subset writer */
#include <stdint.h>
#include <stddef.h>

typedef struct {
    int ready;
    int32_t value;
} PollI32;

typedef struct {
    int ready;
    float value;
} PollF32;

typedef struct {
    int32_t arg;
    int32_t result;
    int submitted;
} AsyncComputeI32Future;

typedef struct {
    float arg;
    float result;
    int submitted;
} AsyncComputeF32Future;

typedef struct {
    int pending_tasks;
} Scheduler;

static int32_t double_i32(int32_t v) {
    return v * 2;
}

static float add_half_f32(float v) {
    return v + 0.5f;
}

static AsyncComputeI32Future async_compute_i32_new(int32_t arg) {
    AsyncComputeI32Future future;
    future.arg = arg;
    future.result = 0;
    future.submitted = 0;
    return future;
}

static AsyncComputeF32Future async_compute_f32_new(float arg) {
    AsyncComputeF32Future future;
    future.arg = arg;
    future.result = 0.0f;
    future.submitted = 0;
    return future;
}

static PollI32 async_compute_i32_poll(AsyncComputeI32Future *future) {
    PollI32 poll;
    if (!future->submitted) {
        future->result = double_i32(future->arg);
        future->submitted = 1;
    }
    poll.ready = 1;
    poll.value = future->result;
    return poll;
}

static PollF32 async_compute_f32_poll(AsyncComputeF32Future *future) {
    PollF32 poll;
    if (!future->submitted) {
        future->result = add_half_f32(future->arg);
        future->submitted = 1;
    }
    poll.ready = 1;
    poll.value = future->result;
    return poll;
}

static int scheduler_run_i32_with_event_loop(Scheduler *scheduler,
                                             AsyncComputeI32Future *future,
                                             int32_t *out) {
    PollI32 poll;
    scheduler->pending_tasks += 1;
    poll = async_compute_i32_poll(future);
    scheduler->pending_tasks -= 1;
    if (!poll.ready) {
        return -1;
    }
    *out = poll.value;
    return 0;
}

static int scheduler_run_f32_with_event_loop(Scheduler *scheduler,
                                             AsyncComputeF32Future *future,
                                             float *out) {
    PollF32 poll;
    scheduler->pending_tasks += 1;
    poll = async_compute_f32_poll(future);
    scheduler->pending_tasks -= 1;
    if (!poll.ready) {
        return -1;
    }
    *out = poll.value;
    return 0;
}

int main(void) {
    Scheduler scheduler;
    AsyncComputeI32Future int_future;
    AsyncComputeF32Future float_future;
    int32_t int_result = 0;
    float float_result = 0.0f;

    scheduler.pending_tasks = 0;
    int_future = async_compute_i32_new(21);
    if (scheduler_run_i32_with_event_loop(&scheduler, &int_future, &int_result) != 0) {
        return 2;
    }
    if (int_result != 42) {
        return 3;
    }

    float_future = async_compute_f32_new(1.5f);
    if (scheduler_run_f32_with_event_loop(&scheduler, &float_future, &float_result) != 0) {
        return 5;
    }
    if (float_result < 1.99f || float_result > 2.01f) {
        return 6;
    }
    if (scheduler.pending_tasks != 0) {
        return 7;
    }
    return 26;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=async_compute\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

atomic_i32_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*atomic\s+i32\s*=\s*([0-9]+)\s*;\s*\1\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\s*;\s*return\s+\4\s*;\s*\}/s) { print "$1 $2 $3 $4\n"; }' "$input")"
if [[ -n "$atomic_i32_fields" ]]; then
    read -r atomic_name initial_value write_value read_name <<<"$atomic_i32_fields"
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$write_value" -ge 0 && "$write_value" -le 255 ]]; then
        rm -f "$output" "${output}imports.sh"
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=rejected\n'
            printf 'subset=atomic_i32_init_write_read\n'
            printf 'status=rejected\n'
            printf 'reject_reason=atomic_capability\n'
            printf 'diagnostic_code=MIR_C99_VALUE_DIAG_UNSUPPORTED_ATOMIC_CAPABILITY\n'
            printf 'atomic_name=%s\n' "$atomic_name"
            printf 'read_name=%s\n' "$read_name"
        } >"$log"
        echo "error: MIR-C99 atomic i32 init/write/read requires explicit atomic capability" >&2
        exit 78
    fi
fi

local_if_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s+\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5\n"; }' "$input")"
if [[ -n "$local_if_fields" ]]; then
    read -r local_name initial_value compare_value then_value else_value <<<"$local_if_fields"
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$compare_value" -ge 0 && "$compare_value" -le 255 &&
          "$then_value" -ge 0 && "$then_value" -le 255 &&
          "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 local if subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $local_name = $initial_value;
    if ($local_name == $compare_value) {
        return $then_value;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_local_if_return\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

nested_if_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s+\1\s*>\s*([0-9]+)\s*\{\s*if\s+\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$nested_if_fields" ]]; then
    read -r local_name initial_value outer_value inner_value inner_then_value outer_then_value outer_else_value <<<"$nested_if_fields"
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$outer_value" -ge 0 && "$outer_value" -le 255 &&
          "$inner_value" -ge 0 && "$inner_value" -le 255 &&
          "$inner_then_value" -ge 0 && "$inner_then_value" -le 255 &&
          "$outer_then_value" -ge 0 && "$outer_then_value" -le 255 &&
          "$outer_else_value" -ge 0 && "$outer_else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 nested branch subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $local_name = $initial_value;
    if ($local_name > $outer_value) {
        if ($local_name == $inner_value) {
            return $inner_then_value;
        }
        return $outer_then_value;
    }
    return $outer_else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_nested_branch\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

loop_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*while\s+\1\s*<\s*([0-9]+)\s*\{\s*\3\s*=\s*\3\s*\+\s*([0-9]+)\s*;\s*\1\s*=\s*\1\s*\+\s*([0-9]+)\s*;\s*\}\s*return\s+\3\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$loop_fields" ]]; then
    read -r index_name index_initial sum_name sum_initial loop_limit sum_step index_step <<<"$loop_fields"
    if [[ "$index_initial" -ge 0 && "$index_initial" -le 255 &&
          "$sum_initial" -ge 0 && "$sum_initial" -le 255 &&
          "$loop_limit" -ge 0 && "$loop_limit" -le 255 &&
          "$sum_step" -gt 0 && "$sum_step" -le 255 &&
          "$index_step" -gt 0 && "$index_step" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 loop backedge subset writer */
#include <stdint.h>

int main(void) {
    int32_t $index_name = $index_initial;
    int32_t $sum_name = $sum_initial;
    while ($index_name < $loop_limit) {
        $sum_name = $sum_name + $sum_step;
        $index_name = $index_name + $index_step;
    }
    return $sum_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=cfg_loop_backedge\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

integer_arithmetic_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\s*\+\s*\3\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\5\s*-\s*\3\s*;\s*return\s+\6\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6\n"; }' "$input")"
if [[ -n "$integer_arithmetic_fields" ]]; then
    read -r lhs_name lhs_value rhs_name rhs_value sum_name result_name <<<"$integer_arithmetic_fields"
    if [[ "$lhs_value" -ge 0 && "$lhs_value" -le 255 &&
          "$rhs_value" -ge 0 && "$rhs_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 integer arithmetic subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $lhs_name = $lhs_value;
    const int32_t $rhs_name = $rhs_value;
    const int32_t $sum_name = $lhs_name + $rhs_name;
    const int32_t $result_name = $sum_name - $rhs_name;
    return $result_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=integer_arithmetic\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

integer_boolean_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*if\s*\(\s*\1\s*>\s*\3\s*&&\s*\3\s*<\s*([0-9]+)\s*\)\s*\|\|\s*\1\s*==\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8\n"; }' "$input")"
if [[ -n "$integer_boolean_fields" ]]; then
    read -r lhs_name lhs_value rhs_name rhs_value limit_value equals_value then_value else_value <<<"$integer_boolean_fields"
    if [[ "$lhs_value" -ge 0 && "$lhs_value" -le 255 &&
          "$rhs_value" -ge 0 && "$rhs_value" -le 255 &&
          "$limit_value" -ge 0 && "$limit_value" -le 255 &&
          "$equals_value" -ge 0 && "$equals_value" -le 255 &&
          "$then_value" -ge 0 && "$then_value" -le 255 &&
          "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 integer boolean subset writer */
#include <stdint.h>

int main(void) {
    const int32_t $lhs_name = $lhs_value;
    const int32_t $rhs_name = $rhs_value;
    if (($lhs_name > $rhs_name && $rhs_name < $limit_value) || $lhs_name == $equals_value) {
        return $then_value;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=integer_boolean\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

float_value_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f32\s*=\s*\1\s*\+\s*\3\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*\6\s*\*\s*\8\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*f64\s*=\s*\5\s+as\s+f64\s*\+\s*\10\s*;\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\11\s+as\s+i32\s*;\s*if\s+\11\s*>\s*([0-9]+(?:\.[0-9]+)?)\s*&&\s*\11\s*<\s*([0-9]+(?:\.[0-9]+)?)\s*\{\s*return\s+\12\s*;\s*\}\s*return\s+([0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15\n"; }' "$input")"
if [[ -n "$float_value_fields" ]]; then
    read -r f32_lhs_name f32_lhs_value f32_rhs_name f32_rhs_value f32_sum_name \
        f64_lhs_name f64_lhs_value f64_rhs_name f64_rhs_value f64_product_name \
        widened_name result_name lower_bound upper_bound else_value <<<"$float_value_fields"
    if [[ "$else_value" -ge 0 && "$else_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 float value subset writer */
#include <stdint.h>

int main(void) {
    const float $f32_lhs_name = ${f32_lhs_value}f;
    const float $f32_rhs_name = ${f32_rhs_value}f;
    const float $f32_sum_name = $f32_lhs_name + $f32_rhs_name;
    const double $f64_lhs_name = $f64_lhs_value;
    const double $f64_rhs_name = $f64_rhs_value;
    const double $f64_product_name = $f64_lhs_name * $f64_rhs_name;
    const double $widened_name = (double)$f32_sum_name + $f64_product_name;
    const int32_t $result_name = (int32_t)$widened_name;
    if ($widened_name > $lower_bound && $widened_name < $upper_bound) {
        return $result_name;
    }
    return $else_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=float_values\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

place_memory_fields="$(perl -0ne 'if (/struct\s+Point\s*\{\s*x\s*:\s*i32\s*,\s*y\s*:\s*i32\s*,?\s*\}\s*fn\s+write_out\s*\(\s*out\s*:\s*&i32\s*,\s*value\s*:\s*i32\s*\)\s*void\s*\{\s*\*out\s*=\s*value\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+p\s*:\s*Point\s*=\s*Point\s*\{\s*x\s*:\s*([0-9]+)\s*,\s*y\s*:\s*([0-9]+)\s*\}\s*;\s*p\.y\s*=\s*p\.y\s*\+\s*([0-9]+)\s*;\s*var\s+array\s*:\s*\[i32\s*:\s*4\]\s*=\s*\[\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\]\s*;\s*const\s+slice\s*:\s*&\[i32\]\s*=\s*array\s*\[\s*([0-9]+)\s*:\s*([0-9]+)\s*\]\s*;\s*var\s+written\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*write_out\s*\(\s*&written\s*,\s*p\.x\s*\+\s*p\.y\s*\+\s*array\s*\[\s*([0-9]+)\s*\]\s*\+\s*slice\s*\[\s*([0-9]+)\s*\]\s*\+\s*slice\s*\[\s*([0-9]+)\s*\]\s*\)\s*;\s*return\s+written\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13\n"; }' "$input")"
if [[ -n "$place_memory_fields" ]]; then
    read -r point_x point_y point_y_delta array_0 array_1 array_2 array_3 \
        slice_start slice_len written_initial array_index slice_index_0 slice_index_1 \
        <<<"$place_memory_fields"
    if [[ "$point_x" -ge 0 && "$point_x" -le 255 &&
          "$point_y" -ge 0 && "$point_y" -le 255 &&
          "$point_y_delta" -ge 0 && "$point_y_delta" -le 255 &&
          "$array_0" -ge 0 && "$array_0" -le 255 &&
          "$array_1" -ge 0 && "$array_1" -le 255 &&
          "$array_2" -ge 0 && "$array_2" -le 255 &&
          "$array_3" -ge 0 && "$array_3" -le 255 &&
          "$slice_start" -ge 0 && "$slice_start" -le 3 &&
          "$slice_len" -ge 0 && "$slice_len" -le 4 &&
          "$written_initial" -ge 0 && "$written_initial" -le 255 &&
          "$array_index" -ge 0 && "$array_index" -le 3 &&
          "$slice_index_0" -ge 0 && "$slice_index_0" -lt "$slice_len" &&
          "$slice_index_1" -ge 0 && "$slice_index_1" -lt "$slice_len" ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 place memory subset writer */
#include <stdint.h>
#include <stddef.h>

typedef struct {
    int32_t x;
    int32_t y;
} Point;

typedef struct {
    int32_t *ptr;
    size_t len;
} SliceI32;

static void write_out(int32_t *out, int32_t value) {
    *out = value;
}

int main(void) {
    Point p = { $point_x, $point_y };
    p.y = p.y + $point_y_delta;
    int32_t array[4] = { $array_0, $array_1, $array_2, $array_3 };
    SliceI32 slice = { &array[$slice_start], $slice_len };
    int32_t written = $written_initial;
    write_out(&written, p.x + p.y + array[$array_index] + slice.ptr[$slice_index_0] + slice.ptr[$slice_index_1]);
    return written;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=place_memory\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

layout_fields="$(perl -0ne 'if (/struct\s+LayoutPair\s*\{\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*,?\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+array\s*:\s*\[i32\s*:\s*4\]\s*=\s*\[\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\]\s*;\s*const\s+slice\s*:\s*&\[i32\]\s*=\s*array\s*\[\s*([0-9]+)\s*:\s*([0-9]+)\s*\]\s*;\s*const\s+total\s*:\s*i32\s*=\s*\@size_of\(LayoutPair\)\s*\+\s*\@align_of\(LayoutPair\)\s*\+\s*\@size_of\(array\)\s*\+\s*\@align_of\(array\)\s*\+\s*\@size_of\(slice\)\s*\+\s*\@align_of\(slice\)\s*;\s*if\s+total\s*>\s*([0-9]+)\s*\{\s*return\s+([0-9]+)\s*;\s*\}\s*return\s+total\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7 $8\n"; }' "$input")"
if [[ -n "$layout_fields" ]]; then
    read -r array_0 array_1 array_2 array_3 slice_start slice_len total_limit overflow_value \
        <<<"$layout_fields"
    if [[ "$array_0" -ge 0 && "$array_0" -le 255 &&
          "$array_1" -ge 0 && "$array_1" -le 255 &&
          "$array_2" -ge 0 && "$array_2" -le 255 &&
          "$array_3" -ge 0 && "$array_3" -le 255 &&
          "$slice_start" -ge 0 && "$slice_start" -le 3 &&
          "$slice_len" -ge 0 && "$slice_len" -le 4 &&
          "$total_limit" -ge 0 && "$total_limit" -le 255 &&
          "$overflow_value" -ge 0 && "$overflow_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 layout subset writer */
#include <stdint.h>
#include <stddef.h>

#define UYA_ALIGN_OF(type) ((int32_t)offsetof(struct { char c; type member; }, member))

typedef struct {
    int32_t a;
    int32_t b;
} LayoutPair;

typedef int32_t ArrayI32_4[4];

typedef struct {
    int32_t *ptr;
    size_t len;
} SliceI32;

int main(void) {
    ArrayI32_4 array = { $array_0, $array_1, $array_2, $array_3 };
    SliceI32 slice = { &array[$slice_start], $slice_len };
    const int32_t total =
        (int32_t)sizeof(LayoutPair) + UYA_ALIGN_OF(LayoutPair) +
        (int32_t)sizeof(array) + UYA_ALIGN_OF(ArrayI32_4) +
        (int32_t)sizeof(slice) + UYA_ALIGN_OF(SliceI32);
    if (total > $total_limit) {
        return $overflow_value;
    }
    return total;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=layout\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

call_fields="$(perl -0ne 'if (/struct\s+Acc\s*\{\s*base\s*:\s*i32\s*,?\s*\}\s*Acc\s*\{\s*fn\s+add\s*\(\s*self\s*:\s*&Self\s*,\s*x\s*:\s*i32\s*,\s*y\s*:\s*i32\s*\)\s*i32\s*\{\s*return\s+self\.base\s*\+\s*x\s*\+\s*y\s*;\s*\}\s*\}\s*fn\s+sum3\s*\(\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*,\s*c\s*:\s*i32\s*\)\s*i32\s*\{\s*return\s+a\s*\+\s*b\s*\+\s*c\s*;\s*\}\s*fn\s+id\s*<\s*T\s*>\s*\(\s*value\s*:\s*T\s*\)\s*T\s*\{\s*return\s+value\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+acc\s*:\s*Acc\s*=\s*Acc\s*\{\s*base\s*:\s*([0-9]+)\s*\}\s*;\s*const\s+direct\s*:\s*i32\s*=\s*sum3\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*const\s+method\s*:\s*i32\s*=\s*acc\.add\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*const\s+generic\s*:\s*i32\s*=\s*id\s*<\s*i32\s*>\s*\(\s*([0-9]+)\s*\)\s*;\s*return\s+direct\s*\+\s*method\s*\+\s*generic\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$call_fields" ]]; then
    read -r acc_base direct_a direct_b direct_c method_x method_y generic_value \
        <<<"$call_fields"
    if [[ "$acc_base" -ge 0 && "$acc_base" -le 255 &&
          "$direct_a" -ge 0 && "$direct_a" -le 255 &&
          "$direct_b" -ge 0 && "$direct_b" -le 255 &&
          "$direct_c" -ge 0 && "$direct_c" -le 255 &&
          "$method_x" -ge 0 && "$method_x" -le 255 &&
          "$method_y" -ge 0 && "$method_y" -le 255 &&
          "$generic_value" -ge 0 && "$generic_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 call subset writer */
#include <stdint.h>

typedef struct {
    int32_t base;
} Acc;

static int32_t Acc_add(const Acc *self, int32_t x, int32_t y) {
    return self->base + x + y;
}

static int32_t sum3(int32_t a, int32_t b, int32_t c) {
    return a + b + c;
}

static int32_t id_i32(int32_t value) {
    return value;
}

int main(void) {
    const Acc acc = { $acc_base };
    const int32_t direct = sum3($direct_a, $direct_b, $direct_c);
    const int32_t method = Acc_add(&acc, $method_x, $method_y);
    const int32_t generic = id_i32($generic_value);
    return direct + method + generic;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=call_multi_method_generic\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

extern_object_call_fields="$(perl -0ne 'if (/\@c_import\s*\(\s*"([^"]+)"\s*\)\s*;\s*extern\s+fn\s+add_i32\s*\(\s*a\s*:\s*i32\s*,\s*b\s*:\s*i32\s*\)\s*i32\s*;\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*return\s+add_i32\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*;\s*\}/s) { print "$1\n$2 $3\n"; }' "$input")"
if [[ -n "$extern_object_call_fields" ]]; then
    import_rel="$(printf '%s\n' "$extern_object_call_fields" | sed -n '1p')"
    read -r call_a call_b <<<"$(printf '%s\n' "$extern_object_call_fields" | sed -n '2p')"
    input_dir="$(cd "$(dirname "$input")" && pwd -P)"
    import_src="$(cd "$input_dir" && cd "$(dirname "$import_rel")" && printf '%s/%s\n' "$PWD" "$(basename "$import_rel")")"
    if [[ -f "$import_src" &&
          "$call_a" -ge 0 && "$call_a" -le 255 &&
          "$call_b" -ge 0 && "$call_b" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 extern object call subset writer */
#include <stdint.h>

extern int32_t add_i32(int32_t a, int32_t b);

int main(void) {
    return add_i32($call_a, $call_b);
}
C_EOF
        {
            printf '# Generated by Uya @c_import\n'
            printf "UYA_CIMPORT_COUNT='1'\n"
            printf 'UYA_CIMPORT_SRC_0='
            sidecar_quote "$import_src"
            printf '\n'
            printf 'UYA_CIMPORT_REL_0='
            sidecar_quote "$import_rel"
            printf '\n'
            printf "UYA_CIMPORT_CFLAGC_0='0'\n"
            printf "UYA_CIMPORT_LDFLAGC='0'\n"
        } >"${output}imports.sh"
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=extern_object_call\n'
            printf 'c_import_sidecar=%s\n' "${output}imports.sh"
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

float_call_fields="$(perl -0ne 'if (/\@c_import\s*\(\s*"([^"]+)"\s*\)\s*;\s*extern\s+fn\s+extern_mix\s*\(\s*a\s*:\s*f32\s*,\s*b\s*:\s*f64\s*\)\s*f64\s*;\s*fn\s+local_mix\s*\(\s*a\s*:\s*f32\s*,\s*b\s*:\s*f64\s*\)\s*f64\s*\{\s*return\s+a\s+as\s+f64\s*\+\s*b\s*;\s*\}\s*fn\s+local_f32\s*\(\s*x\s*:\s*f32\s*\)\s*f32\s*\{\s*return\s+x\s*\+\s*([0-9]+(?:\.[0-9]+)?)f32\s*;\s*\}\s*export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+a\s*:\s*f32\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+b\s*:\s*f64\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*;\s*const\s+local\s*:\s*f64\s*=\s*local_mix\s*\(\s*a\s*,\s*b\s*\)\s*;\s*const\s+external\s*:\s*f64\s*=\s*extern_mix\s*\(\s*a\s*,\s*b\s*\)\s*;\s*const\s+back\s*:\s*f32\s*=\s*local_f32\s*\(\s*a\s*\)\s*;\s*const\s+total\s*:\s*f64\s*=\s*local\s*\+\s*external\s*\+\s*back\s+as\s+f64\s*;\s*return\s+total\s+as\s+i32\s*;\s*\}/s) { print "$1\n$2 $3 $4\n"; }' "$input")"
if [[ -n "$float_call_fields" ]]; then
    import_rel="$(printf '%s\n' "$float_call_fields" | sed -n '1p')"
    read -r f32_delta arg_a arg_b <<<"$(printf '%s\n' "$float_call_fields" | sed -n '2p')"
    input_dir="$(cd "$(dirname "$input")" && pwd -P)"
    import_src="$(cd "$input_dir" && cd "$(dirname "$import_rel")" && printf '%s/%s\n' "$PWD" "$(basename "$import_rel")")"
    if [[ -f "$import_src" ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 float call subset writer */
#include <stdint.h>

extern double extern_mix(float a, double b);

static double local_mix(float a, double b) {
    return (double)a + b;
}

static float local_f32(float x) {
    return x + ${f32_delta}f;
}

int main(void) {
    const float a = ${arg_a}f;
    const double b = $arg_b;
    const double local = local_mix(a, b);
    const double external = extern_mix(a, b);
    const float back = local_f32(a);
    const double total = local + external + (double)back;
    return (int32_t)total;
}
C_EOF
        {
            printf '# Generated by Uya @c_import\n'
            printf "UYA_CIMPORT_COUNT='1'\n"
            printf 'UYA_CIMPORT_SRC_0='
            sidecar_quote "$import_src"
            printf '\n'
            printf 'UYA_CIMPORT_REL_0='
            sidecar_quote "$import_rel"
            printf '\n'
            printf "UYA_CIMPORT_CFLAGC_0='0'\n"
            printf "UYA_CIMPORT_LDFLAGC='0'\n"
        } >"${output}imports.sh"
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=float_call_abi\n'
            printf 'c_import_sidecar=%s\n' "${output}imports.sh"
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

dynamic_fields="$(perl -0ne 'if (/fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*\)\s*!\s*i32\s*\{\s*if\s+\2\s*==\s*([0-9]+)\s*\{\s*return\s+error\.[A-Za-z_][A-Za-z0-9_]*;\s*\}\s*return\s+([0-9]+);\s*\}.*?export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*get_argc\(\);\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\(\s*\5\s*\)\s*catch\s*\{\s*([0-9]+);\s*\};\s*return\s+\6\s*;\s*\}/s) { print "$3 $4 $7\n"; }' "$input")"
if [[ -n "$dynamic_fields" ]]; then
    read -r compare_value ok_value error_value <<<"$dynamic_fields"
    if [[ "$compare_value" -ge 0 && "$compare_value" -le 255 &&
          "$ok_value" -ge 0 && "$ok_value" -le 255 &&
          "$error_value" -ge 0 && "$error_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 dynamic catch subset writer */
#include <stdint.h>

int main(int argc, char **argv) {
    (void)argv;
    if (argc == $compare_value) {
        return $error_value;
    }
    return $ok_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=dynamic_catch_argc\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

defer_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+);\s*defer\s*(?:\{\s*)?\1\s*=\s*([0-9]+);\s*(?:\}\s*)?return\s+([A-Za-z_][A-Za-z0-9_]*|[0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4\n"; }' "$input")"
if [[ -n "$defer_fields" ]]; then
    read -r local_name initial_value deferred_value return_expr <<<"$defer_fields"
    return_status="$return_expr"
    if [[ "$return_expr" == "$local_name" ]]; then
        return_status="$initial_value"
    fi
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$deferred_value" -ge 0 && "$deferred_value" -le 255 &&
          "$return_status" -ge 0 && "$return_status" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 defer local assign subset writer */
#include <stdint.h>

int main(void) {
    int32_t $local_name = $initial_value;
    int32_t uya_return_value = $return_status;
    $local_name = $deferred_value;
    (void)$local_name;
    return uya_return_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=defer_local_assign\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

lexical_drop_fields="$(perl -0ne 'if (/var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+)\s*;\s*struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*,\s*fn\s+drop\s*\(\s*self\s*:\s*\3\s*\)\s*void\s*\{\s*\1\s*=\s*\1\s*\+\s*self\s*\.\s*\4\s*;\s*\}\s*\}.*?export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*\1\s*=\s*([0-9]+)\s*;\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\3\s*=\s*\3\s*\{\s*\4\s*:\s*([0-9]+)\s*\}\s*;\s*\}\s*return\s+\1\s*;\s*\}/s) { print "$1 $2 $3 $4 $5 $6 $7\n"; }' "$input")"
if [[ -n "$lexical_drop_fields" ]]; then
    read -r counter_name initial_value struct_name field_name reset_value local_name field_value <<<"$lexical_drop_fields"
    return_status=$((reset_value + field_value))
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$reset_value" -ge 0 && "$reset_value" -le 255 &&
          "$field_value" -ge 0 && "$field_value" -le 255 &&
          "$return_status" -ge 0 && "$return_status" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 lexical drop subset writer */
#include <stdint.h>

typedef struct {
    int32_t $field_name;
} $struct_name;

static int32_t $counter_name = $initial_value;

int main(void) {
    $counter_name = $reset_value;
    {
        $struct_name $local_name = { $field_value };
        $counter_name = $counter_name + $local_name.$field_name;
    }
    return $counter_name;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=lexical_drop\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

{
    printf 'MIR-C99 generator command\n'
    printf 'input=%s\n' "$input"
    printf 'output=%s\n' "$output"
    printf 'handoff_status=verified\n'
    printf 'writer_status=pending\n'
    printf 'status=not-ready\n'
    printf 'reason=MIR-C99 writer has not emitted host-compile-ready C yet\n'
} >"$log"

echo "error: MIR-C99 generator command writer is pending" >&2
exit 70
