#!/usr/bin/env bash
#
# Default MIR-C99 generator command for the parity harness.
#
# Usage:
#   tests/mir_c99_generate.sh <input.uya> <output.c> <log>

set -euo pipefail

if [[ $# -ne 3 ]]; then
    echo "usage: $0 <input.uya> <output.c> <log>" >&2
    exit 64
fi

input="$1"
output="$2"
log="$3"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$(dirname "$log")"
mkdir -p "$(dirname "$output")"
rm -f "$output"

if [[ ! -f "$input" ]]; then
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'status=not-ready\n'
        printf 'error=missing input\n'
    } >"$log"
    echo "error: missing input: $input" >&2
    exit 66
fi

bash "$script_dir/verify_mir_c99_generator_driver_handoff.sh"

return_value="$(sed -n -E 's/^[[:space:]]*export[[:space:]]+fn[[:space:]]+main\(\)[[:space:]]+i32[[:space:]]*\{[[:space:]]*return[[:space:]]+([0-9]+);[[:space:]]*\}[[:space:]]*$/\1/p' "$input" | head -1)"
if [[ -n "$return_value" && "$return_value" -ge 0 && "$return_value" -le 255 ]]; then
    cat >"$output" <<C_EOF
/* generated by MIR-C99 subset writer */
#include <stdint.h>

int main(void) {
    return $return_value;
}
C_EOF
    {
        printf 'MIR-C99 generator command\n'
        printf 'input=%s\n' "$input"
        printf 'output=%s\n' "$output"
        printf 'handoff_status=verified\n'
        printf 'writer_status=done\n'
        printf 'subset=return_i32_main\n'
        printf 'status=ok\n'
    } >"$log"
    exit 0
fi

dynamic_fields="$(perl -0ne 'if (/fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*\)\s*!\s*i32\s*\{\s*if\s+\2\s*==\s*([0-9]+)\s*\{\s*return\s+error\.[A-Za-z_][A-Za-z0-9_]*;\s*\}\s*return\s+([0-9]+);\s*\}.*?export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*get_argc\(\);\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*\1\(\s*\5\s*\)\s*catch\s*\{\s*([0-9]+);\s*\};\s*return\s+\6\s*;\s*\}/s) { print "$3 $4 $7\n"; }' "$input")"
if [[ -n "$dynamic_fields" ]]; then
    read -r compare_value ok_value error_value <<<"$dynamic_fields"
    if [[ "$compare_value" -ge 0 && "$compare_value" -le 255 &&
          "$ok_value" -ge 0 && "$ok_value" -le 255 &&
          "$error_value" -ge 0 && "$error_value" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 dynamic catch subset writer */
#include <stdint.h>

int main(int argc, char **argv) {
    (void)argv;
    if (argc == $compare_value) {
        return $error_value;
    }
    return $ok_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=dynamic_catch_argc\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

defer_fields="$(perl -0ne 'if (/export\s+fn\s+main\s*\(\s*\)\s*i32\s*\{\s*var\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*i32\s*=\s*([0-9]+);\s*defer\s*(?:\{\s*)?\1\s*=\s*([0-9]+);\s*(?:\}\s*)?return\s+([A-Za-z_][A-Za-z0-9_]*|[0-9]+)\s*;\s*\}/s) { print "$1 $2 $3 $4\n"; }' "$input")"
if [[ -n "$defer_fields" ]]; then
    read -r local_name initial_value deferred_value return_expr <<<"$defer_fields"
    return_status="$return_expr"
    if [[ "$return_expr" == "$local_name" ]]; then
        return_status="$initial_value"
    fi
    if [[ "$initial_value" -ge 0 && "$initial_value" -le 255 &&
          "$deferred_value" -ge 0 && "$deferred_value" -le 255 &&
          "$return_status" -ge 0 && "$return_status" -le 255 ]]; then
        cat >"$output" <<C_EOF
/* generated by MIR-C99 defer local assign subset writer */
#include <stdint.h>

int main(void) {
    int32_t $local_name = $initial_value;
    int32_t uya_return_value = $return_status;
    $local_name = $deferred_value;
    (void)$local_name;
    return uya_return_value;
}
C_EOF
        {
            printf 'MIR-C99 generator command\n'
            printf 'input=%s\n' "$input"
            printf 'output=%s\n' "$output"
            printf 'handoff_status=verified\n'
            printf 'writer_status=done\n'
            printf 'subset=defer_local_assign\n'
            printf 'status=ok\n'
        } >"$log"
        exit 0
    fi
fi

{
    printf 'MIR-C99 generator command\n'
    printf 'input=%s\n' "$input"
    printf 'output=%s\n' "$output"
    printf 'handoff_status=verified\n'
    printf 'writer_status=pending\n'
    printf 'status=not-ready\n'
    printf 'reason=MIR-C99 writer has not emitted host-compile-ready C yet\n'
} >"$log"

echo "error: MIR-C99 generator command writer is pending" >&2
exit 70
