#!/usr/bin/env bash
#
# Real-CLI gate for MIR-C99 test/no-main entry handling.
#
# This gate must:
#   - build a current-source cmd/build candidate via the fixed ../uya/bin/uya path;
#   - prove mainful input still emits real MIR-C99 C;
#   - reject test-only and no-main inputs without falling back to legacy C99 or a
#     fake `int main(void) { return uya_mir_fn_N(); }` wrapper.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-test-no-main.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

BOOTSTRAP_BIN="$TMP_DIR/build-bootstrap"
CANDIDATE_BIN="$TMP_DIR/cmd-build-candidate"

helper_case="$TMP_DIR/helper_only.uya"
extern_case="$TMP_DIR/extern_only.uya"
decl_case="$TMP_DIR/decl_only.uya"

cat >"$helper_case" <<'UYA'
fn helper() i32 {
    return 42;
}
UYA

cat >"$extern_case" <<'UYA'
extern fn add(a: i32, b: i32) i32;
UYA

cat >"$decl_case" <<'UYA'
struct Payload {
    value: i32,
}

const DEFAULT_VALUE: i32 = 7;
UYA

fail() {
    echo "error: $*" >&2
    exit 1
}

build_candidate() {
    local bootstrap_log="$TMP_DIR/build_bootstrap.generate.log"
    local candidate_log="$TMP_DIR/cmd_build_candidate.generate.log"

    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT" "$COMPILER" build \
            src/cmd/build_bootstrap/main.uya -o "$BOOTSTRAP_BIN" \
            --project-root "$REPO_ROOT/src/" --no-split-c
    ) >"$bootstrap_log" 2>&1 || {
        cat "$bootstrap_log" >&2
        fail "failed to build bootstrap cmd/build helper"
    }
    [[ -x "$BOOTSTRAP_BIN" ]] || fail "bootstrap binary is not executable: $BOOTSTRAP_BIN"

    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT" "$BOOTSTRAP_BIN" build \
            src/cmd/build/main.uya -o "$CANDIDATE_BIN" \
            --project-root "$REPO_ROOT/src/" --no-split-c
    ) >"$candidate_log" 2>&1 || {
        cat "$candidate_log" >&2
        fail "failed to build current-source cmd/build candidate"
    }
    [[ -x "$CANDIDATE_BIN" ]] || fail "candidate binary is not executable: $CANDIDATE_BIN"
}

reject_legacy_output() {
    local output="$1"
    if [[ ! -s "$output" ]]; then
        fail "missing generated output: $output"
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$output"; then
        fail "output still contains legacy C99 banner: $output"
    fi
    if grep -Eq 'int main\(void\)[[:space:]]*\{[[:space:]]*return uya_mir_fn_[0-9]+\(\);[[:space:]]*\}' "$output"; then
        fail "output still contains fake MIR-C99 main wrapper: $output"
    fi
}

run_expect_success() {
    local name="$1"
    local input="$2"
    local project_root="$3"
    local output="$4"
    local log="$5"

    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT" "$CANDIDATE_BIN" build --mir-c99 "$input" -o "$output" \
            --project-root "$project_root" --no-split-c
    ) >"$log" 2>&1 || {
        cat "$log" >&2
        fail "$name should succeed under real current-source --mir-c99"
    }
    grep -q '\[MIR-C99\]' "$log" || fail "$name log is missing [MIR-C99] evidence"
    grep -q 'generated by MIR-C99 unit output writer' "$output" || {
        cat "$log" >&2
        fail "$name output is missing MIR-C99 writer banner"
    }
    reject_legacy_output "$output"
}

run_expect_diag() {
    local name="$1"
    local input="$2"
    local project_root="$3"
    local output="$4"
    local log="$5"
    local pattern="$6"

    set +e
    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT" "$CANDIDATE_BIN" build --mir-c99 "$input" -o "$output" \
            --project-root "$project_root" --no-split-c
    ) >"$log" 2>&1
    local status=$?
    set -e

    if [[ $status -eq 0 ]]; then
        cat "$log" >&2
        fail "$name should fail closed under real current-source --mir-c99"
    fi
    grep -q '\[MIR-C99\]' "$log" || fail "$name log is missing [MIR-C99] evidence"
    grep -q "$pattern" "$log" || {
        cat "$log" >&2
        fail "$name log is missing expected diagnostic pattern: $pattern"
    }
    if [[ -e "$output" && -s "$output" ]]; then
        reject_legacy_output "$output"
        fail "$name left a non-empty output after fail-closed diagnostic: $output"
    fi
}

if [[ ! -x "$COMPILER" ]]; then
    fail "missing fixed compiler path: $COMPILER"
fi

build_candidate

run_expect_success \
    "HelloWorld real CLI" \
    "$REPO_ROOT/examples/HelloWorld.uya" \
    "$REPO_ROOT" \
    "$TMP_DIR/hello.c" \
    "$TMP_DIR/hello.log"

run_expect_diag \
    "test array bounds shard" \
    "$REPO_ROOT/tests/test_array_bounds.uya" \
    "$REPO_ROOT" \
    "$TMP_DIR/test_array_bounds.c" \
    "$TMP_DIR/test_array_bounds.log" \
    'mir_c99_capability_diagnostic: kind=AST_TEST_STMT reason=test_driver_not_lowered'

run_expect_diag \
    "test block comment shard" \
    "$REPO_ROOT/tests/test_block_comment.uya" \
    "$REPO_ROOT" \
    "$TMP_DIR/test_block_comment.c" \
    "$TMP_DIR/test_block_comment.log" \
    'mir_c99_capability_diagnostic: kind=AST_TEST_STMT reason=test_driver_not_lowered'

run_expect_diag \
    "helper-only module" \
    "$helper_case" \
    "$TMP_DIR" \
    "$TMP_DIR/helper_only.c" \
    "$TMP_DIR/helper_only.log" \
    'mir_c99_capability_diagnostic: kind=PROGRAM_ENTRY reason=no_main_entrypoint'

run_expect_diag \
    "extern-only module" \
    "$extern_case" \
    "$TMP_DIR" \
    "$TMP_DIR/extern_only.c" \
    "$TMP_DIR/extern_only.log" \
    'mir_c99_capability_diagnostic: kind=PROGRAM_ENTRY reason=no_main_entrypoint'

run_expect_diag \
    "declaration-only module" \
    "$decl_case" \
    "$TMP_DIR" \
    "$TMP_DIR/decl_only.c" \
    "$TMP_DIR/decl_only.log" \
    'mir_c99_capability_diagnostic: kind=PROGRAM_ENTRY reason=no_main_entrypoint'

echo "OK: MIR-C99 real current-source CLI rejects test/no-main false positives without fake main fallback"
