#!/usr/bin/env bash
#
# Async cleanup/resource MIR-C99 real-CLI parity shard: async error-union
# cleanup, async defer/errdefer execution, and frame release/resource cleanup.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 async cleanup/resource compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-async-cleanup.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

run_case() {
    local name="$1"
    local body="$2"
    local case_file="$tmp_dir/${name}.uya"
    printf '%s\n' "$body" >"$case_file"
    build_and_compare_case "$name" "$case_file"
}

compile_host_c() {
    local input_c="$1"
    local output_bin="$2"
    local sidecar_file="${input_c}imports.sh"
    local object_dir="${output_bin}.objects"
    local -a link_cmd=("$HOST_CC" -std=c99 -Wall -Wextra -pedantic "$input_c")
    local -a cimport_objects=()

    if [[ -f "$sidecar_file" ]]; then
        mkdir -p "$object_dir"
        # shellcheck disable=SC1090
        . "$sidecar_file"
        local ci=0
        while [[ "$ci" -lt "${UYA_CIMPORT_COUNT:-0}" ]]; do
            local src_var="UYA_CIMPORT_SRC_${ci}"
            local cflag_count_var="UYA_CIMPORT_CFLAGC_${ci}"
            local src_path="${!src_var}"
            local cflag_count="${!cflag_count_var:-0}"
            local obj_path="$object_dir/cimport_${ci}.o"
            local -a compile_cmd=("$HOST_CC" -std=c99 -Wall -Wextra -pedantic -c)
            local cj=0
            while [[ "$cj" -lt "$cflag_count" ]]; do
                local cflag_var="UYA_CIMPORT_CFLAG_${ci}_${cj}"
                compile_cmd+=("${!cflag_var}")
                cj=$((cj + 1))
            done
            compile_cmd+=("$src_path" -o "$obj_path")
            "${compile_cmd[@]}"
            cimport_objects+=("$obj_path")
            ci=$((ci + 1))
        done
        link_cmd+=("${cimport_objects[@]}")
        local ldflag_count="${UYA_CIMPORT_LDFLAGC:-0}"
        local li=0
        while [[ "$li" -lt "$ldflag_count" ]]; do
            local ldflag_var="UYA_CIMPORT_LDFLAG_${li}"
            link_cmd+=("${!ldflag_var}")
            li=$((li + 1))
        done
    fi

    link_cmd+=(-o "$output_bin")
    if ! "${link_cmd[@]}" >"$tmp_dir/$(basename "$output_bin").cc.out" 2>"$tmp_dir/$(basename "$output_bin").cc.err"; then
        echo "error: host C compile failed for $input_c" >&2
        cat "$tmp_dir/$(basename "$output_bin").cc.out" >&2 || true
        cat "$tmp_dir/$(basename "$output_bin").cc.err" >&2 || true
        exit 1
    fi
}

run_binary_capture() {
    local bin="$1"
    local prefix="$2"
    set +e
    "$bin" >"$prefix.stdout" 2>"$prefix.stderr"
    local status=$?
    set -e
    printf '%s\n' "$status" >"$prefix.exit"
}

build_and_compare_case() {
    local case_name="$1"
    local case_file="$2"
    local mir_c="$tmp_dir/${case_name}.mir.c"
    local mir_bin="$tmp_dir/${case_name}.mir"
    local oracle_c="$tmp_dir/${case_name}.oracle.c"
    local oracle_bin="$tmp_dir/${case_name}.oracle"
    local mir_log="$tmp_dir/${case_name}.mir.log"
    local oracle_log="$tmp_dir/${case_name}.oracle.log"

    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT/lib/" "$COMPILER" build --mir-c99 "$case_file" \
            -o "$mir_c" --project-root "$tmp_dir"
    ) >"$mir_log" 2>&1
    (
        cd "$REPO_ROOT"
        UYA_ROOT="$REPO_ROOT/lib/" "$COMPILER" build --c99 "$case_file" \
            -o "$oracle_c" --no-split-c --project-root "$tmp_dir"
    ) >"$oracle_log" 2>&1

    if ! grep -q '\[MIR-C99\]' "$mir_log"; then
        echo "error: $case_name did not enter the real --mir-c99 route" >&2
        sed -n '1,120p' "$mir_log" >&2
        exit 1
    fi
    if ! grep -q 'generated by MIR-C99 unit output writer' "$mir_c"; then
        echo "error: $case_name did not emit MIR-C99 unit-output C" >&2
        sed -n '1,80p' "$mir_c" >&2
        exit 1
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$mir_c"; then
        echo "error: $case_name real-CLI probe fell back to legacy C99 output" >&2
        sed -n '1,80p' "$mir_c" >&2
        exit 1
    fi

    compile_host_c "$mir_c" "$mir_bin"
    compile_host_c "$oracle_c" "$oracle_bin"

    run_binary_capture "$mir_bin" "$tmp_dir/${case_name}.candidate"
    run_binary_capture "$oracle_bin" "$tmp_dir/${case_name}.oracle"

    diff -u "$tmp_dir/${case_name}.oracle.stdout" "$tmp_dir/${case_name}.candidate.stdout"
    diff -u "$tmp_dir/${case_name}.oracle.stderr" "$tmp_dir/${case_name}.candidate.stderr"
    diff -u "$tmp_dir/${case_name}.oracle.exit" "$tmp_dir/${case_name}.candidate.exit"
}

run_case "async_cleanup_resource" '// mir_c99_async_cleanup_resource_case
use std.async;

var cleanup_marker: i32 = 0;

error AsyncCleanupFailure;

fn ready_i32_cleanup(v: i32) Future<!i32> {
    const p: Poll<!i32> = Poll<!i32>.Ready(ok<i32>(v));
    return Future<!i32>{ state: p };
}

@async_fn
fn cleanup_async(flag: i32) Future<!i32> {
    const awaited: i32 = try @await ready_i32_cleanup(flag + 2);
    const value: i32 = try cleanup_inner(flag, awaited);
    return value;
}

fn cleanup_inner(flag: i32, awaited: i32) !i32 {
    cleanup_marker = 1;
    defer { cleanup_marker = cleanup_marker + 10; }
    errdefer { cleanup_marker = cleanup_marker + 40; }
    if flag != 0 {
        return error.AsyncCleanupFailure;
    }
    return awaited + cleanup_marker;
}

export fn main() i32 {
    cleanup_marker = 0;
    const ok_r: !i32 = block_on<i32>(cleanup_async(0));
    const ok_v: i32 = ok_r catch { return 1; };
    if ok_v != 3 || cleanup_marker != 11 {
        return 2;
    }

    cleanup_marker = 0;
    const err_r: !i32 = block_on<i32>(cleanup_async(1));
    var err_seen: i32 = 0;
    const err_v: i32 = err_r catch {
        err_seen = 1;
        0 - 5;
    };
    if err_seen != 1 || err_v != 0 - 5 || cleanup_marker != 51 {
        return 3;
    }
    return 17;
}'

run_case "async_frame_release_resource" '// mir_c99_async_frame_release_resource_case
use std.async;

var frame_release_marker: i32 = 0;

struct ReleaseOnStopFuture : Future<!i32> {
    value: i32,

    fn poll(self: &Self, waker: &Waker) Poll<!i32> {
        _ = self;
        _ = waker;
        return Poll<!i32>.Pending({});
    }

    fn release(self: &Self) void {
        frame_release_marker = frame_release_marker + self.value;
    }
}

fn pending_release_child(value: i32) Future<!i32> {
    return ReleaseOnStopFuture{ value: value };
}

@async_fn
fn frame_release_child(value: i32) Future<!i32> {
    const waited: i32 = try @await pending_release_child(value);
    return waited + 1;
}

export fn main() i32 {
    var frame: @frame(frame_release_child);
    const w: Waker = Waker{};

    frame_release_marker = 0;
    frame.start(6);
    const first_poll: Poll<!i32> = frame.poll(&w);
    var first_pending: i32 = 0;
    match first_poll {
        .Pending(_) => { first_pending = 1; },
        .Ready(_) => { first_pending = 0; },
    };
    frame.stop();
    if first_pending != 1 || frame_release_marker != 6 {
        return 1;
    }

    frame.start(8);
    const second_poll: Poll<!i32> = frame.poll(&w);
    var second_pending: i32 = 0;
    match second_poll {
        .Pending(_) => { second_pending = 1; },
        .Ready(_) => { second_pending = 0; },
    };
    frame.stop();
    if second_pending != 1 || frame_release_marker != 14 {
        return 2;
    }

    return 23;
}'

echo "OK: MIR-C99 async cleanup/resource real-CLI parity matched C99 oracle"
