#!/usr/bin/env bash
#
# Real fixed-CLI gate for the first MIR-C99 extern-lowering bucket.
#
# This gate must:
#   - run the exact fixed `../uya/bin/uya build --mir-c99 tests/assignment.uya`
#     acceptance path;
#   - forbid the old generic `错误: MIR-C99 extern lowering 失败`;
#   - require either a stable `mir_c99_capability_diagnostic:` line or a real
#     successful MIR-C99 output.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FIXED_UYA="$REPO_ROOT/../uya/bin/uya"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-extern-capability.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

ASSIGNMENT_LOG="$TMP_DIR/assignment.log"
ASSIGNMENT_OUT="$TMP_DIR/assignment.c"

fail() {
    echo "error: $*" >&2
    exit 1
}

if [[ ! -x "$FIXED_UYA" ]]; then
    fail "missing fixed compiler path: $FIXED_UYA"
fi

set +e
(
    cd "$REPO_ROOT"
    UYA_ROOT="$REPO_ROOT/lib/" "$FIXED_UYA" build \
        --mir-c99 tests/assignment.uya -o "$ASSIGNMENT_OUT"
) >"$ASSIGNMENT_LOG" 2>&1
status=$?
set -e

grep -Fq '[MIR-C99]' "$ASSIGNMENT_LOG" || {
    cat "$ASSIGNMENT_LOG" >&2
    fail "assignment log is missing [MIR-C99] routing evidence"
}

if grep -Fq '错误: MIR-C99 extern lowering 失败' "$ASSIGNMENT_LOG"; then
    cat "$ASSIGNMENT_LOG" >&2
    fail "assignment log still contains the generic extern lowering failure"
fi

if grep -Fq '错误: MIR-C99 PortableMIR lowering 尚未覆盖当前程序' "$ASSIGNMENT_LOG"; then
    cat "$ASSIGNMENT_LOG" >&2
    fail "assignment log still falls through to the generic PortableMIR lowering failure"
fi

if [[ "$status" -eq 0 ]]; then
    if [[ ! -s "$ASSIGNMENT_OUT" ]]; then
        cat "$ASSIGNMENT_LOG" >&2
        fail "assignment MIR-C99 success did not leave a non-empty output: $ASSIGNMENT_OUT"
    fi
    grep -Fq 'generated by MIR-C99 unit output writer' "$ASSIGNMENT_OUT" || {
        cat "$ASSIGNMENT_LOG" >&2
        fail "assignment MIR-C99 success is missing the MIR-C99 writer banner"
    }
    echo "OK: MIR-C99 assignment extern bucket now succeeds without generic extern lowering"
    exit 0
fi

grep -Eq 'mir_c99_capability_diagnostic: kind=AST_TEST_STMT reason=test_driver_not_lowered file=tests/assignment\.uya line=6' "$ASSIGNMENT_LOG" || {
    cat "$ASSIGNMENT_LOG" >&2
    fail "assignment fail-closed path is missing the expected AST_TEST_STMT capability diagnostic"
}

if [[ -e "$ASSIGNMENT_OUT" && -s "$ASSIGNMENT_OUT" ]]; then
    cat "$ASSIGNMENT_LOG" >&2
    fail "assignment reject left a non-empty MIR-C99 output: $ASSIGNMENT_OUT"
fi

echo "OK: MIR-C99 assignment extern bucket now fails closed with explicit capability diagnostic"
