#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
tmp_dir="$(mktemp -d /tmp/uya-mir-c99-cli-distinct.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

hello_c="$tmp_dir/hello.c"
main_c="$tmp_dir/main.c"
hello_log="$tmp_dir/hello.log"
main_log="$tmp_dir/main.log"

require_real_mir_output() {
    local label="$1"
    local log_file="$2"
    local output_c="$3"

    if ! grep -q '\[MIR-C99\]' "$log_file"; then
        echo "error: $label did not enter the real --mir-c99 route" >&2
        sed -n '1,160p' "$log_file" >&2 || true
        exit 1
    fi
    if ! grep -q 'generated by MIR-C99 unit output writer' "$output_c"; then
        echo "error: $label did not emit MIR-C99 unit-output C" >&2
        sed -n '1,60p' "$output_c" >&2 || true
        exit 1
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$output_c"; then
        echo "error: $label produced legacy C99 output" >&2
        sed -n '1,60p' "$output_c" >&2 || true
        exit 1
    fi
}

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

"$COMPILER" build --mir-c99 "$REPO_ROOT/examples/HelloWorld.uya" -o "$hello_c" >"$hello_log" 2>&1
"$COMPILER" build --mir-c99 "$REPO_ROOT/src/main.uya" -o "$main_c" >"$main_log" 2>&1

require_real_mir_output "HelloWorld CLI" "$hello_log" "$hello_c"
require_real_mir_output "src/main.uya CLI" "$main_log" "$main_c"

if cmp -s "$hello_c" "$main_c"; then
    echo "error: different --mir-c99 inputs produced identical C output" >&2
    exit 1
fi

test -s "$hello_c"
test -s "$main_c"

echo "OK: uya build --mir-c99 emits distinct C for distinct inputs"
