#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d /tmp/uya-mir-c99-cli-helloworld.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

out_c="$tmp_dir/helloworld.c"
out_exe="$tmp_dir/helloworld"
build_log="$tmp_dir/build.log"
run_log="$tmp_dir/run.log"

"$REPO_ROOT/bin/uya" build --mir-c99 "$REPO_ROOT/examples/HelloWorld.uya" -o "$out_c" >"$build_log" 2>&1

grep -q '\[MIR-C99\]' "$build_log"
grep -q 'generated by MIR-C99 unit output writer' "$out_c"
grep -q 'Hello, World!' "$out_c"
if grep -q 'C99 代码由 Uya Mini 编译器生成' "$out_c"; then
    echo "error: --mir-c99 produced legacy C99 output" >&2
    exit 1
fi

cc -std=c99 "$out_c" -o "$out_exe"
"$out_exe" >"$run_log"
grep -q 'Hello, World!' "$run_log"
grep -q '欢迎使用 Uya 编程语言！' "$run_log"

echo "OK: uya build --mir-c99 examples/HelloWorld.uya emits and runs MIR-C99 C"
