#!/usr/bin/env bash
#
# MIR-C99 self-build preflight: default generator must emit a real compiler
# candidate C for the build-only compiler root, compile with the host C
# compiler, and pass a minimal --help smoke test.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CMD_BUILD_SOURCE="$REPO_ROOT/src/cmd/build/main.uya"
BUILD_DRIVER="$REPO_ROOT/src/build_compiler_driver.uya"
GENERATOR="$REPO_ROOT/tests/mir_c99_generate.sh"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-cmd-build-preflight.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! grep -Eq "$pattern" "$file"; then
        echo "error: missing cmd/build MIR-C99 self-build evidence: $description" >&2
        echo "file: $file" >&2
        exit 1
    fi
}

if [[ ! -f "$CMD_BUILD_SOURCE" ]]; then
    echo "error: missing cmd/build self-build root: $CMD_BUILD_SOURCE" >&2
    exit 1
fi

require_pattern "$CMD_BUILD_SOURCE" '^use build_compiler_driver;' \
    "cmd/build root imports build-only compiler driver"
require_pattern "$CMD_BUILD_SOURCE" 'export[[:space:]]+fn[[:space:]]+main\(\)[[:space:]]+i32' \
    "cmd/build root exports process main"
require_pattern "$CMD_BUILD_SOURCE" 'return[[:space:]]+build_compiler_driver_main\(\);' \
    "cmd/build root delegates to build_compiler_driver_main"
require_pattern "$BUILD_DRIVER" 'fn[[:space:]]+native_build_hosted_mir_c99_preflight' \
    "build driver exposes hosted MIR-C99 preflight"
require_pattern "$BUILD_DRIVER" 'native_build_hosted_mir_append_program_safe_bodies' \
    "MIR-C99 preflight consumes source-to-PortableMIR body lowering"
require_pattern "$BUILD_DRIVER" 'portable_mir_backend_request_init\(&request,[^;]+MIR_TARGET_BACKEND_C99' \
    "MIR-C99 preflight creates a C99 backend request"
require_pattern "$BUILD_DRIVER" 'mir_c99_driver_run\(&request,' \
    "MIR-C99 preflight reaches MirC99Plan driver"
require_pattern "$BUILD_DRIVER" 'MIR_BACKEND_OUTPUT_MIR_C99_PLAN' \
    "MIR-C99 preflight records MirC99Plan output kind"

stdout_file="$TMP_DIR/generator.out"
stderr_file="$TMP_DIR/generator.err"
output_c="$TMP_DIR/cmd-build-mir.c"
log_file="$TMP_DIR/cmd-build-mir.log"
summary_file="${output_c}.summary"
bin_file="$TMP_DIR/cmd-build-mir-candidate.bin"
run_stdout="$TMP_DIR/run.out"
run_stderr="$TMP_DIR/run.err"

set +e
"$GENERATOR" "$CMD_BUILD_SOURCE" "$output_c" "$log_file" >"$stdout_file" 2>"$stderr_file"
status=$?
set -e

if [[ "$status" -ne 0 ]]; then
    echo "error: cmd/build MIR-C99 self-build generator failed" >&2
    cat "$stdout_file" >&2
    cat "$stderr_file" >&2
    exit 1
fi
if [[ ! -s "$output_c" ]]; then
    echo "error: cmd/build MIR-C99 generator did not leave C output" >&2
    ls -l "$TMP_DIR" >&2
    exit 1
fi
if [[ ! -f "$log_file" ]]; then
    echo "error: cmd/build MIR-C99 preflight did not write a diagnostic log" >&2
    exit 1
fi
if [[ ! -s "$summary_file" ]]; then
    echo "error: cmd/build MIR-C99 generator did not write summary sidecar" >&2
    ls -l "$TMP_DIR" >&2
    exit 1
fi
require_pattern "$log_file" 'handoff_status=verified' \
    "default generator verified source-to-PortableMIR/MirC99Plan handoff"
require_pattern "$log_file" 'writer_status=done' \
    "default generator wrote cmd/build C output"
require_pattern "$log_file" 'subset=cmd_build_real_candidate' \
    "default generator records real candidate subset"
require_pattern "$log_file" 'compiler_binary_status=generated' \
    "default generator reports compiler binary generated"
require_pattern "$log_file" 'host_compiler_binary_candidate_role=compiler_binary' \
    "default generator reports compiler binary role"
require_pattern "$log_file" 'status=ok' \
    "default generator reports real candidate output success"
require_pattern "$log_file" 'input=.*/src/cmd/build/main\.uya' \
    "diagnostic log records cmd/build source root"
require_pattern "$log_file" 'summary_sidecar=.*/cmd-build-mir\.c\.summary' \
    "diagnostic log records summary sidecar path"
require_pattern "$summary_file" '^MIR_C99_CMD_BUILD_SUMMARY=1$' \
    "summary sidecar records cmd/build summary marker"
require_pattern "$summary_file" '^MIR_C99_HANDOFF_STATUS='\''verified'\''$' \
    "summary sidecar records verified handoff"
require_pattern "$summary_file" '^MIR_C99_COMPILER_BINARY_STATUS='\''generated'\''$' \
    "summary sidecar records compiler binary generated"
require_pattern "$summary_file" '^MIR_C99_HOST_COMPILER_BINARY_CANDIDATE_ROLE='\''compiler_binary'\''$' \
    "summary sidecar records compiler binary candidate role"
require_pattern "$summary_file" '^MIR_C99_COMPILER_SOURCE_BACKEND='\''mir_c99_unit_output'\''$' \
    "summary sidecar records the compiler source backend used for the candidate"
require_pattern "$output_c" 'generated by MIR-C99 unit output writer' \
    "C output identifies real MIR-C99 unit output C"

cc -std=c99 -Wall -Wextra -pedantic "$output_c" -o "$bin_file" -lm
set +e
"$bin_file" --help >"$run_stdout" 2>"$run_stderr"
run_status=$?
set -e

if [[ "$run_status" -ne 0 ]]; then
    echo "error: cmd/build real candidate executable should exit 0 on --help, got $run_status" >&2
    cat "$run_stdout" >&2
    cat "$run_stderr" >&2
    exit 1
fi
if ! grep -Eq 'Uya build compiler' "$run_stdout" "$run_stderr"; then
    echo "error: missing cmd/build MIR-C99 self-build evidence: real candidate executable identifies as Uya build compiler" >&2
    echo "stdout file: $run_stdout" >&2
    echo "stderr file: $run_stderr" >&2
    exit 1
fi
if ! grep -Eq '用法:' "$run_stdout" "$run_stderr"; then
    echo "error: missing cmd/build MIR-C99 self-build evidence: real candidate executable prints usage in Chinese" >&2
    echo "stdout file: $run_stdout" >&2
    echo "stderr file: $run_stderr" >&2
    exit 1
fi

if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' \
    "$log_file" "$summary_file" "$stdout_file" "$stderr_file" "$run_stdout" "$run_stderr"; then
    echo "error: cmd/build MIR-C99 preflight mentioned legacy C99 fallback" >&2
    cat "$log_file" >&2
    cat "$summary_file" >&2
    cat "$stdout_file" >&2
    cat "$stderr_file" >&2
    cat "$run_stdout" >&2
    cat "$run_stderr" >&2
    exit 1
fi

echo "OK: cmd/build MIR-C99 self-build root emits real compiler candidate C and passes --help smoke"
