#!/usr/bin/env bash
#
# Focused real-CLI harness for MIR-C99 interface call surface coverage.
#
# This gate must use ../uya/bin/uya directly. It only counts as success when
# both the basic interface-dispatch and generic interface-dispatch fixtures
# enter the real --mir-c99 route, produce MIR-C99 unit-output C, and match the
# legacy C99 oracle after host C compilation. If either fixture silently falls
# back to legacy C99, the gate fails.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 interface-call compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-interface-call-real-cli.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

compile_host_c() {
    local input_c="$1"
    local output_bin="$2"
    if ! "$HOST_CC" -std=c99 -Wall -Wextra -pedantic "$input_c" -o "$output_bin" \
        >"$tmp_dir/$(basename "$output_bin").cc.out" \
        2>"$tmp_dir/$(basename "$output_bin").cc.err"; then
        echo "error: host C compile failed for $input_c" >&2
        cat "$tmp_dir/$(basename "$output_bin").cc.out" >&2 || true
        cat "$tmp_dir/$(basename "$output_bin").cc.err" >&2 || true
        exit 1
    fi
}

run_binary_capture() {
    local bin="$1"
    local prefix="$2"
    set +e
    "$bin" >"$prefix.stdout" 2>"$prefix.stderr"
    local status=$?
    set -e
    printf '%s\n' "$status" >"$prefix.exit"
}

build_and_compare_case() {
    local case_name="$1"
    local case_file="$2"
    local mir_c="$tmp_dir/${case_name}.mir.c"
    local mir_bin="$tmp_dir/${case_name}.mir"
    local oracle_c="$tmp_dir/${case_name}.oracle.c"
    local oracle_bin="$tmp_dir/${case_name}.oracle"
    local mir_log="$tmp_dir/${case_name}.mir.log"
    local oracle_log="$tmp_dir/${case_name}.oracle.log"

    "$COMPILER" build --mir-c99 "$case_file" -o "$mir_c" --no-split-c --project-root "$REPO_ROOT" \
        >"$mir_log" 2>&1
    "$COMPILER" build --c99 "$case_file" -o "$oracle_c" --no-split-c --project-root "$REPO_ROOT" \
        >"$oracle_log" 2>&1

    if ! grep -q '\[MIR-C99\]' "$mir_log"; then
        echo "error: $case_name did not enter the real --mir-c99 route" >&2
        sed -n '1,120p' "$mir_log" >&2
        exit 1
    fi
    if ! grep -q 'generated by MIR-C99 unit output writer' "$mir_c"; then
        echo "error: $case_name did not emit MIR-C99 unit-output C" >&2
        sed -n '1,40p' "$mir_c" >&2
        exit 1
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$mir_c"; then
        echo "error: $case_name real-CLI probe fell back to legacy C99 output" >&2
        sed -n '1,40p' "$mir_c" >&2
        exit 1
    fi

    compile_host_c "$mir_c" "$mir_bin"
    compile_host_c "$oracle_c" "$oracle_bin"

    run_binary_capture "$mir_bin" "$tmp_dir/${case_name}.candidate"
    run_binary_capture "$oracle_bin" "$tmp_dir/${case_name}.oracle"

    diff -u "$tmp_dir/${case_name}.oracle.stdout" "$tmp_dir/${case_name}.candidate.stdout"
    diff -u "$tmp_dir/${case_name}.oracle.stderr" "$tmp_dir/${case_name}.candidate.stderr"
    diff -u "$tmp_dir/${case_name}.oracle.exit" "$tmp_dir/${case_name}.candidate.exit"
}

build_and_compare_case interface_dispatch \
    "$REPO_ROOT/tests/fixtures/mir_c99_cmd_build_full_language_interface_dispatch.uya"
build_and_compare_case generic_interface_dispatch \
    "$REPO_ROOT/tests/fixtures/mir_c99_cmd_build_full_language_generic_interface.uya"

echo "OK: MIR-C99 real CLI interface call surface parity matched C99 oracle"
