#!/usr/bin/env bash
#
# Focused real-CLI harness for MIR-C99 runtime helper / print / params coverage.
#
# This gate must use ../uya/bin/uya directly. It only counts as success when:
#   1. the parent preflight `tests/extern_function.uya` enters the real
#      `--mir-c99` route;
#   2. focused stdout/stderr + print, env/file/heap/string, source-location,
#      and `@params` cases all enter the real `--mir-c99` route;
#   3. the emitted C is MIR-C99 unit-output C, not legacy C99 fallback; and
#   4. host C compilation / execution matches the legacy `--c99` oracle,
#      including file side effects for the env/file helper case.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 runtime-helper compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi
if ! command -v "$HOST_CC" >/dev/null 2>&1; then
    echo "error: host C compiler is missing: $HOST_CC" >&2
    exit 70
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-runtime-helper-real-cli.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

compile_c() {
    local input_c="$1"
    local output_bin="$2"
    local link_out="$tmp_dir/$(basename "$output_bin").cc.out"
    local link_err="$tmp_dir/$(basename "$output_bin").cc.err"
    if ! "$HOST_CC" -std=c99 -Wall -Wextra -pedantic "$input_c" -o "$output_bin" \
        >"$link_out" 2>"$link_err"; then
        echo "error: host C compile failed for $input_c" >&2
        cat "$link_out" >&2 || true
        cat "$link_err" >&2 || true
        exit 1
    fi
}

run_binary_capture() {
    local bin="$1"
    local prefix="$2"
    local work_dir="$3"
    set +e
    (
        cd "$work_dir"
        UYA_MIR_C99_HELPER_ENV="runtime-helper-env" \
            "$bin" >"$prefix.stdout" 2>"$prefix.stderr"
    )
    local status=$?
    set -e
    printf '%s\n' "$status" >"$prefix.exit"
}

build_and_compare_case() {
    local case_name="$1"
    local case_file="$2"
    local project_root="$3"
    local artifact_name="${4:-}"
    local mir_c="$tmp_dir/${case_name}.mir.c"
    local mir_bin="$tmp_dir/${case_name}.mir"
    local oracle_c="$tmp_dir/${case_name}.oracle.c"
    local oracle_bin="$tmp_dir/${case_name}.oracle"
    local mir_log="$tmp_dir/${case_name}.mir.log"
    local oracle_log="$tmp_dir/${case_name}.oracle.log"
    local candidate_work="$tmp_dir/${case_name}.candidate.work"
    local oracle_work="$tmp_dir/${case_name}.oracle.work"

    mkdir -p "$candidate_work" "$oracle_work"

    if ! "$COMPILER" build --mir-c99 "$case_file" -o "$mir_c" --no-split-c \
        --project-root "$project_root" >"$mir_log" 2>&1; then
        echo "error: $case_name real --mir-c99 build failed before parity comparison" >&2
        sed -n '1,160p' "$mir_log" >&2 || true
        exit 1
    fi
    "$COMPILER" build --c99 "$case_file" -o "$oracle_c" --no-split-c \
        --project-root "$project_root" >"$oracle_log" 2>&1

    if ! grep -q '\[MIR-C99\]' "$mir_log"; then
        echo "error: $case_name did not enter the real --mir-c99 route" >&2
        sed -n '1,160p' "$mir_log" >&2 || true
        exit 1
    fi
    if ! grep -q 'generated by MIR-C99 unit output writer' "$mir_c"; then
        echo "error: $case_name did not emit MIR-C99 unit-output C" >&2
        sed -n '1,60p' "$mir_c" >&2 || true
        exit 1
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$mir_c"; then
        echo "error: $case_name real-CLI probe fell back to legacy C99 output" >&2
        sed -n '1,60p' "$mir_c" >&2 || true
        exit 1
    fi

    compile_c "$mir_c" "$mir_bin"
    compile_c "$oracle_c" "$oracle_bin"

    run_binary_capture "$mir_bin" "$tmp_dir/${case_name}.candidate" "$candidate_work"
    run_binary_capture "$oracle_bin" "$tmp_dir/${case_name}.oracle" "$oracle_work"

    diff -u "$tmp_dir/${case_name}.oracle.stdout" "$tmp_dir/${case_name}.candidate.stdout"
    diff -u "$tmp_dir/${case_name}.oracle.stderr" "$tmp_dir/${case_name}.candidate.stderr"
    diff -u "$tmp_dir/${case_name}.oracle.exit" "$tmp_dir/${case_name}.candidate.exit"

    if [[ -n "$artifact_name" ]]; then
        if [[ ! -f "$candidate_work/$artifact_name" ]]; then
            echo "error: $case_name candidate did not write runtime artifact $artifact_name" >&2
            exit 1
        fi
        if [[ ! -f "$oracle_work/$artifact_name" ]]; then
            echo "error: $case_name oracle did not write runtime artifact $artifact_name" >&2
            exit 1
        fi
        diff -u "$oracle_work/$artifact_name" "$candidate_work/$artifact_name"
    fi
}

preflight_c="$tmp_dir/extern_function_preflight.c"
preflight_log="$tmp_dir/extern_function_preflight.log"
if ! "$COMPILER" build --mir-c99 "$REPO_ROOT/tests/extern_function.uya" -o "$preflight_c" \
    >"$preflight_log" 2>&1; then
    echo "error: fixed compiler preflight failed closed before runtime-helper shard" >&2
    sed -n '1,160p' "$preflight_log" >&2 || true
    exit 1
fi
if ! grep -q '\[MIR-C99\]' "$preflight_log"; then
    echo "error: fixed compiler preflight did not enter the real --mir-c99 route for tests/extern_function.uya" >&2
    sed -n '1,160p' "$preflight_log" >&2 || true
    exit 1
fi
if ! grep -q 'generated by MIR-C99 unit output writer' "$preflight_c"; then
    echo "error: fixed compiler preflight did not emit MIR-C99 unit-output C" >&2
    sed -n '1,60p' "$preflight_c" >&2 || true
    exit 1
fi
if grep -q 'C99 代码由 Uya Mini 编译器生成' "$preflight_c"; then
    echo "error: fixed compiler preflight fell back to legacy C99 output" >&2
    sed -n '1,60p' "$preflight_c" >&2 || true
    exit 1
fi

cat >"$tmp_dir/print_stdout_stderr.uya" <<'UYA'
use libc;
use libc.fprintf;

export fn main() i32 {
    const stdout_rc: i32 = fprintf(libc.stdout, "stdout:%d\n", 7);
    const stderr_rc: i32 = fprintf(libc.stderr, "stderr:%d\n", 11);
    const print_rc: i32 = @print("print:");
    const println_rc: i32 = @println("ok");
    if stdout_rc <= 0 || stderr_rc <= 0 {
        return 1;
    }
    if print_rc < 0 || println_rc < 0 {
        return 2;
    }
    return 0;
}
UYA

cat >"$tmp_dir/runtime_helper_env_file_heap_string.uya" <<'UYA'
use libc.FILE;
use libc.fclose;
use libc.fopen;
use libc.fputs;
use libc.free;
use libc.getenv;
use libc.malloc;
use libc.memset;
use libc.strlen;

export fn main() i32 {
    const env: *byte = getenv("UYA_MIR_C99_HELPER_ENV" as *byte);
    if env == null || env[0] == 0 {
        return 11;
    }
    const env_len: usize = strlen(env as *const byte);
    const buf: *byte = malloc(5usize);
    if buf == null {
        return 12;
    }
    _ = memset(buf, 65, 4usize);
    buf[4] = 0;
    const file: &FILE = fopen("runtime_helper_env_file.txt\0" as &const byte,
        "w\0" as &const byte);
    if file == null {
        free(buf);
        return 13;
    }
    const write_rc: i32 = fputs(buf as &const byte, file);
    _ = fclose(file);
    free(buf);
    if write_rc < 0 {
        return 14;
    }
    return env_len as i32 + 1;
}
UYA

cat >"$tmp_dir/source_location_builtins.uya" <<'UYA'
use libc.strlen;

fn inspect_location() i32 {
    const name: *byte = @src_name;
    const path: *byte = @src_path;
    const line: i32 = @src_line;
    const col: i32 = @src_col;
    const func: *byte = @func_name;
    if name == null || path == null || func == null {
        return 21;
    }
    if line <= 0 || col <= 0 {
        return 22;
    }
    if strlen(name as *const byte) == 0usize ||
       strlen(path as *const byte) == 0usize ||
       strlen(func as *const byte) == 0usize {
        return 23;
    }
    return 0;
}

export fn main() i32 {
    return inspect_location();
}
UYA

cat >"$tmp_dir/params_tuple_surface.uya" <<'UYA'
fn add_pair(a: i32, b: i32) i32 {
    const pair: (i32, i32) = @params;
    return pair.0 + pair.1;
}

fn fuse_three(a: i32, b: i32, c: i32) i32 {
    const values: (i32, i32, i32) = @params;
    return values.0 * values.1 + values.2;
}

export fn main() i32 {
    if add_pair(19, 23) != 42 {
        return 31;
    }
    if fuse_three(6, 7, 5) != 47 {
        return 32;
    }
    return 0;
}
UYA

build_and_compare_case print_stdout_stderr \
    "$tmp_dir/print_stdout_stderr.uya" "$tmp_dir"
build_and_compare_case runtime_helper_env_file_heap_string \
    "$tmp_dir/runtime_helper_env_file_heap_string.uya" "$tmp_dir" \
    "runtime_helper_env_file.txt"
build_and_compare_case source_location_builtins \
    "$tmp_dir/source_location_builtins.uya" "$tmp_dir"
build_and_compare_case params_tuple_surface \
    "$tmp_dir/params_tuple_surface.uya" "$tmp_dir"

echo "OK: MIR-C99 real CLI runtime helper / print / params parity matched C99 oracle"
