#!/usr/bin/env bash
#
# Focused real-CLI harness for the statement/CFG MIR-C99 shard.
#
# This gate intentionally uses ../uya/bin/uya directly.  It proves the shard has
# a real --mir-c99 CLI entry, a host-C99 compile/run oracle, and fail-closed
# evidence for statement/CFG shapes not covered by the current lowering yet.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 shard compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-stmt-cfg-cli.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

statement_case="$tmp_dir/statement_return_literal.uya"
cfg_frontier_case="$tmp_dir/cfg_branch_loop_frontier.uya"

cat >"$statement_case" <<'UYA'
export fn main() i32 {
    return 7;
}
UYA

cat >"$cfg_frontier_case" <<'UYA'
export fn main() i32 {
    var acc: i32 = 0;
    var i: i32 = 0;
    while i < 3 {
        if i < 2 {
            acc = acc + 2;
        } else {
            acc = acc + 1;
        }
        i = i + 1;
    }
    return acc;
}
UYA

mir_c="$tmp_dir/statement_return_literal.mir.c"
oracle_c="$tmp_dir/statement_return_literal.oracle.c"
mir_bin="$tmp_dir/statement_return_literal.mir"
oracle_bin="$tmp_dir/statement_return_literal.oracle"
mir_build_log="$tmp_dir/statement_return_literal.mir.build.log"
oracle_build_log="$tmp_dir/statement_return_literal.oracle.build.log"
cfg_c="$tmp_dir/cfg_branch_loop_frontier.mir.c"
cfg_build_log="$tmp_dir/cfg_branch_loop_frontier.mir.build.log"

"$COMPILER" build --mir-c99 "$statement_case" -o "$mir_c" --project-root "$REPO_ROOT" \
    >"$mir_build_log" 2>&1
"$COMPILER" build --c99 "$statement_case" -o "$oracle_c" --no-split-c --project-root "$REPO_ROOT" \
    >"$oracle_build_log" 2>&1

grep -q '\[MIR-C99\]' "$mir_build_log"
grep -q 'generated by MIR-C99 unit output writer' "$mir_c"
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$mir_build_log" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$mir_c"; then
    echo "error: real --mir-c99 statement shard showed legacy fallback evidence" >&2
    exit 1
fi

"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$mir_c" -o "$mir_bin"
"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$oracle_c" -o "$oracle_bin"

set +e
"$mir_bin" >"$tmp_dir/mir.stdout" 2>"$tmp_dir/mir.stderr"
mir_status=$?
"$oracle_bin" >"$tmp_dir/oracle.stdout" 2>"$tmp_dir/oracle.stderr"
oracle_status=$?
set -e

printf '%s\n' "$mir_status" >"$tmp_dir/mir.exit"
printf '%s\n' "$oracle_status" >"$tmp_dir/oracle.exit"
diff -u "$tmp_dir/oracle.stdout" "$tmp_dir/mir.stdout"
diff -u "$tmp_dir/oracle.stderr" "$tmp_dir/mir.stderr"
diff -u "$tmp_dir/oracle.exit" "$tmp_dir/mir.exit"

set +e
"$COMPILER" build --mir-c99 "$cfg_frontier_case" -o "$cfg_c" --project-root "$REPO_ROOT" \
    >"$cfg_build_log" 2>&1
cfg_status=$?
set -e

if [[ "$cfg_status" -eq 0 ]]; then
    echo "error: CFG frontier unexpectedly passed; promote it into the positive statement/CFG shard cases" >&2
    exit 1
fi
grep -q '\[MIR-C99\]' "$cfg_build_log"
grep -Eq 'MIR-C99 PortableMIR (lowering 尚未覆盖当前程序|verifier 失败)' "$cfg_build_log"
if [[ -s "$cfg_c" ]] && grep -q 'C99 代码由 Uya Mini 编译器生成' "$cfg_c"; then
    echo "error: unsupported CFG frontier wrote legacy C99 output" >&2
    exit 1
fi
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$cfg_build_log"; then
    echo "error: unsupported CFG frontier mentioned legacy fallback" >&2
    exit 1
fi

echo "OK: MIR-C99 statement/CFG shard real CLI harness used $COMPILER, compiled statement C, matched C99 oracle, and failed closed for CFG frontier"
