#!/usr/bin/env bash
#
# MIR-C99 self-build preflight and summary writer for the build-only compiler root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CMD_BUILD_SOURCE="$REPO_ROOT/src/cmd/build/main.uya"
BUILD_DRIVER="$REPO_ROOT/src/build_compiler_driver.uya"
GENERATOR="$REPO_ROOT/tests/mir_c99_generate.sh"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-cmd-build-preflight.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! grep -Eq "$pattern" "$file"; then
        echo "error: missing cmd/build MIR-C99 self-build evidence: $description" >&2
        echo "file: $file" >&2
        exit 1
    fi
}

if [[ ! -f "$CMD_BUILD_SOURCE" ]]; then
    echo "error: missing cmd/build self-build root: $CMD_BUILD_SOURCE" >&2
    exit 1
fi

require_pattern "$CMD_BUILD_SOURCE" '^use build_compiler_driver;' \
    "cmd/build root imports build-only compiler driver"
require_pattern "$CMD_BUILD_SOURCE" 'export[[:space:]]+fn[[:space:]]+main\(\)[[:space:]]+i32' \
    "cmd/build root exports process main"
require_pattern "$CMD_BUILD_SOURCE" 'return[[:space:]]+build_compiler_driver_main\(\);' \
    "cmd/build root delegates to build_compiler_driver_main"
require_pattern "$BUILD_DRIVER" 'fn[[:space:]]+native_build_hosted_mir_c99_preflight' \
    "build driver exposes hosted MIR-C99 preflight"
require_pattern "$BUILD_DRIVER" 'native_build_hosted_mir_append_program_safe_bodies' \
    "MIR-C99 preflight consumes source-to-PortableMIR body lowering"
require_pattern "$BUILD_DRIVER" 'portable_mir_backend_request_init\(&request,[^;]+MIR_TARGET_BACKEND_C99' \
    "MIR-C99 preflight creates a C99 backend request"
require_pattern "$BUILD_DRIVER" 'mir_c99_driver_run\(&request,' \
    "MIR-C99 preflight reaches MirC99Plan driver"
require_pattern "$BUILD_DRIVER" 'MIR_BACKEND_OUTPUT_MIR_C99_PLAN' \
    "MIR-C99 preflight records MirC99Plan output kind"

stdout_file="$TMP_DIR/generator.out"
stderr_file="$TMP_DIR/generator.err"
output_c="$TMP_DIR/cmd-build-mir.c"
log_file="$TMP_DIR/cmd-build-mir.log"
summary_file="${output_c}.summary"
bin_file="$TMP_DIR/cmd-build-mir-summary.bin"
run_stdout="$TMP_DIR/run.out"
run_stderr="$TMP_DIR/run.err"

set +e
"$GENERATOR" "$CMD_BUILD_SOURCE" "$output_c" "$log_file" >"$stdout_file" 2>"$stderr_file"
status=$?
set -e

if [[ "$status" -ne 0 ]]; then
    echo "error: cmd/build MIR-C99 self-build summary writer failed" >&2
    cat "$stdout_file" >&2
    cat "$stderr_file" >&2
    exit 1
fi
if [[ ! -s "$output_c" ]]; then
    echo "error: cmd/build MIR-C99 summary writer did not leave C output" >&2
    ls -l "$TMP_DIR" >&2
    exit 1
fi
if [[ ! -f "$log_file" ]]; then
    echo "error: cmd/build MIR-C99 preflight did not write a diagnostic log" >&2
    exit 1
fi
if [[ ! -s "$summary_file" ]]; then
    echo "error: cmd/build MIR-C99 summary writer did not write summary sidecar" >&2
    ls -l "$TMP_DIR" >&2
    exit 1
fi
require_pattern "$log_file" 'handoff_status=verified' \
    "default generator verified source-to-PortableMIR/MirC99Plan handoff"
require_pattern "$log_file" 'writer_status=done' \
    "default generator wrote cmd/build summary C output"
require_pattern "$log_file" 'subset=cmd_build_self_summary' \
    "default generator records cmd/build summary subset"
require_pattern "$log_file" 'compiler_binary_status=not_yet_generated' \
    "default generator does not claim compiler binary output"
require_pattern "$log_file" 'status=ok' \
    "default generator reports summary output success"
require_pattern "$log_file" 'input=.*/src/cmd/build/main\.uya' \
    "diagnostic log records cmd/build source root"
require_pattern "$log_file" 'summary_sidecar=.*/cmd-build-mir\.c\.summary' \
    "diagnostic log records summary sidecar path"
require_pattern "$summary_file" '^MIR_C99_CMD_BUILD_SUMMARY=1$' \
    "summary sidecar records cmd/build summary marker"
require_pattern "$summary_file" '^MIR_C99_HANDOFF_STATUS='\''verified'\''' \
    "summary sidecar records verified handoff"
require_pattern "$summary_file" '^MIR_C99_COMPILER_BINARY_STATUS='\''not_yet_generated'\''' \
    "summary sidecar records non-compiler status"
require_pattern "$output_c" 'generated by MIR-C99 cmd/build self-build summary writer' \
    "C output identifies summary writer"
require_pattern "$output_c" 'compiler_binary_status=not_yet_generated' \
    "C output reports non-compiler status when executed"

cc -std=c99 -Wall -Wextra -pedantic "$output_c" -o "$bin_file"
set +e
"$bin_file" >"$run_stdout" 2>"$run_stderr"
run_status=$?
set -e

if [[ "$run_status" -ne 70 ]]; then
    echo "error: cmd/build summary executable should exit 70, got $run_status" >&2
    cat "$run_stdout" >&2
    cat "$run_stderr" >&2
    exit 1
fi
require_pattern "$run_stderr" 'mir_c99_cmd_build_summary' \
    "summary executable reports summary role"
require_pattern "$run_stderr" 'compiler_binary_status=not_yet_generated' \
    "summary executable reports non-compiler status"

if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' \
    "$log_file" "$summary_file" "$output_c" "$stdout_file" "$stderr_file" "$run_stdout" "$run_stderr"; then
    echo "error: cmd/build MIR-C99 preflight mentioned legacy C99 fallback" >&2
    cat "$log_file" >&2
    cat "$summary_file" >&2
    cat "$output_c" >&2
    cat "$stdout_file" >&2
    cat "$stderr_file" >&2
    cat "$run_stdout" >&2
    cat "$run_stderr" >&2
    exit 1
fi

echo "OK: cmd/build MIR-C99 self-build root emits summary-only C output"
