#!/usr/bin/env bash
#
# MIR-C99 cmd/build generator must use the real MIR-C99 writer, not the
# transitional tracked cmd/build seed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATOR="$REPO_ROOT/tests/mir_c99_generate.sh"
CMD_BUILD_SOURCE="$REPO_ROOT/src/cmd/build/main.uya"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-cmd-build-true-writer.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! grep -Eq "$pattern" "$file"; then
        echo "error: missing MIR-C99 true writer evidence: $description" >&2
        echo "file: $file" >&2
        exit 1
    fi
}

reject_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if grep -Eq "$pattern" "$file"; then
        echo "error: forbidden MIR-C99 true writer evidence: $description" >&2
        echo "file: $file" >&2
        exit 1
    fi
}

output_c="$TMP_DIR/cmd-build-mir.c"
log_file="$TMP_DIR/cmd-build-mir.log"
summary_file="${output_c}.summary"
object_file="$TMP_DIR/cmd-build-mir.o"

MIR_C99_SKIP_HANDOFF_VERIFY=1 "$GENERATOR" "$CMD_BUILD_SOURCE" "$output_c" "$log_file" >/dev/null

test -s "$output_c"
test -s "$log_file"
test -s "$summary_file"

require_pattern "$log_file" '^handoff_status=verified$' \
    "generator verified source-to-PortableMIR and mir_c99_driver_run handoff"
require_pattern "$log_file" '^writer_status=done$' \
    "generator completed the cmd/build writer"
require_pattern "$log_file" '^compiler_source_backend=mir_c99_unit_output$' \
    "diagnostic log records real MIR-C99 unit output backend"
require_pattern "$summary_file" "^MIR_C99_COMPILER_SOURCE_BACKEND='mir_c99_unit_output'$" \
    "summary records real MIR-C99 unit output backend"
require_pattern "$output_c" 'generated by MIR-C99 unit output writer' \
    "C output identifies the MIR-C99 unit output writer"
require_pattern "$output_c" 'uya_mir_func_' \
    "C output contains MIR-C99 function symbols"

reject_pattern "$log_file" 'tracked_cmd_build_seed|backup/cmd-build' \
    "diagnostic log must not reference tracked cmd/build seed"
reject_pattern "$summary_file" 'tracked_cmd_build_seed|backup/cmd-build' \
    "summary must not reference tracked cmd/build seed"
reject_pattern "$output_c" 'C99 代码由 Uya Mini 编译器生成|Uya build compiler - C99 build seed' \
    "C output must not be copied from the tracked cmd/build seed"

cc -std=c99 -Wall -Wextra -pedantic -c "$output_c" -o "$object_file"

echo "OK: MIR-C99 cmd/build generator uses real unit output writer instead of tracked seed"
