#!/usr/bin/env bash
#
# Full-language MIR-C99 baseline truth gate.
#
# This gate keeps the current full-language baseline honest: HelloWorld success,
# hosted native parity, fixture-generator output, or legacy C99 success must not
# be counted as end-to-end MIR-C99 full-language parity.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FIXED_UYA="$REPO_ROOT/../uya/bin/uya"
TMP_DIR="$(mktemp -d /tmp/uya-mir-c99-full-language-baseline.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

fail() {
    echo "error: $*" >&2
    exit 1
}

require_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if ! grep -Eq -- "$pattern" "$file"; then
        echo "error: missing full-language MIR-C99 baseline evidence: $description" >&2
        echo "file: $file" >&2
        if [[ -f "$file" ]]; then
            sed -n '1,120p' "$file" >&2
        fi
        exit 1
    fi
}

reject_pattern() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    if grep -Eq -- "$pattern" "$file"; then
        echo "error: full-language MIR-C99 baseline accepted forbidden evidence: $description" >&2
        echo "file: $file" >&2
        sed -n '1,120p' "$file" >&2
        exit 1
    fi
}

run_expect_failure() {
    local label="$1"
    local log_file="$2"
    shift 2
    set +e
    "$@" >"$log_file" 2>&1
    local status=$?
    set -e
    if [[ "$status" -eq 0 ]]; then
        echo "error: $label unexpectedly succeeded" >&2
        sed -n '1,120p' "$log_file" >&2
        exit 1
    fi
}

if [[ ! -x "$FIXED_UYA" ]]; then
    fail "missing fixed compiler path ../uya/bin/uya; this gate refuses PATH, UYA_BIN, --uya-bin, and local bin/uya fallback"
fi

hello_c="$TMP_DIR/helloworld.mir.c"
hello_log="$TMP_DIR/helloworld.mir.log"
"$FIXED_UYA" build --mir-c99 "$REPO_ROOT/examples/HelloWorld.uya" -o "$hello_c" >"$hello_log" 2>&1
require_pattern "$hello_log" '\[MIR-C99\]' 'HelloWorld build entered the --mir-c99 route'
require_pattern "$hello_c" 'generated by MIR-C99 unit output writer' 'HelloWorld output is marked as MIR-C99 unit output'
reject_pattern "$hello_c" 'C99 代码由 Uya Mini 编译器生成' 'HelloWorld MIR-C99 output must not be legacy C99'

main_c="$TMP_DIR/src-main.mir.c"
main_log="$TMP_DIR/src-main.mir.log"
run_expect_failure "src/main.uya --mir-c99 full-language baseline" "$main_log" \
    "$FIXED_UYA" build --mir-c99 "$REPO_ROOT/src/main.uya" -o "$main_c"
require_pattern "$main_log" 'MIR-C99 PortableMIR lowering 尚未覆盖当前程序' \
    'src/main.uya still fails closed on unsupported full-language PortableMIR lowering'
if [[ -s "$main_c" ]]; then
    fail "src/main.uya --mir-c99 left a non-empty output after failing closed"
fi

extern_c="$TMP_DIR/extern-function.mir.c"
extern_log="$TMP_DIR/extern-function.mir.log"
run_expect_failure "tests/extern_function.uya --mir-c99 output baseline" "$extern_log" \
    "$FIXED_UYA" build --mir-c99 "$REPO_ROOT/tests/extern_function.uya" -o "$extern_c"
require_pattern "$extern_log" 'MIR-C99 unit output 写出失败' \
    'tests/extern_function.uya still fails closed on MIR-C99 unit output write'
if [[ -s "$extern_c" ]]; then
    fail "tests/extern_function.uya --mir-c99 left a non-empty output after failing closed"
fi

portable_log="$TMP_DIR/portable-coverage.log"
bash "$REPO_ROOT/tests/verify_portable_mir_language_coverage.sh" >"$portable_log" 2>&1
require_pattern "$portable_log" 'OK:|✓|portable' 'PortableMIR language coverage gate ran as a separate coverage check'

native_gate="$REPO_ROOT/tests/verify_full_language_backend_parity.sh"
require_pattern "$native_gate" 'UYA_FULL_LANGUAGE_PARITY_NATIVE' \
    'hosted native parity gate is explicitly native-scoped'
require_pattern "$native_gate" '--native' \
    'hosted native parity gate invokes native backend, not --mir-c99'
reject_pattern "$native_gate" '--mir-c99' \
    'hosted native parity gate must not be mistaken for --mir-c99 evidence'

fixture_case="$TMP_DIR/fixture-generator-main.uya"
fixture_c="$TMP_DIR/fixture-generator.c"
fixture_log="$TMP_DIR/fixture-generator.log"
fixture_stdout="$TMP_DIR/fixture-generator.stdout"
fixture_stderr="$TMP_DIR/fixture-generator.stderr"
printf 'fn helper() i32 { return 1; }\nexport fn main() i32 { return helper(); }\n' >"$fixture_case"
set +e
bash "$REPO_ROOT/tests/mir_c99_generate.sh" "$fixture_case" "$fixture_c" "$fixture_log" \
    >"$fixture_stdout" 2>"$fixture_stderr"
fixture_status=$?
set -e
if [[ "$fixture_status" -eq 0 ]]; then
    fail "fixture generator unexpectedly succeeded on a generic full-language baseline case"
fi
if [[ -s "$fixture_c" ]]; then
    fail "fixture generator left C output on an unsupported generic full-language case"
fi
require_pattern "$fixture_log" 'source-to-PortableMIR|mir_c99_driver_run|MIR-C99 generator command' \
    'fixture generator records a fail-closed hookup diagnostic'
reject_pattern "$fixture_log" 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' \
    'fixture generator must not fall back to legacy C99'

legacy_out="$TMP_DIR/legacy-c99-output"
legacy_log="$TMP_DIR/legacy-c99.log"
"$FIXED_UYA" build "$REPO_ROOT/examples/HelloWorld.uya" -o "$legacy_out" >"$legacy_log" 2>&1
reject_pattern "$legacy_log" '\[MIR-C99\]' 'legacy C99 success must not be classified as --mir-c99'

echo "baseline_mir_c99_helloworld=pass"
echo "baseline_mir_c99_src_main=fail_closed:portable_mir_lowering_missing"
echo "baseline_mir_c99_extern_function=fail_closed:unit_output_write_failed"
echo "baseline_hosted_native=classified_native_only"
echo "baseline_fixture_generator=classified_fail_closed_only"
echo "baseline_legacy_c99=classified_not_mir_c99"
echo "OK: full-language MIR-C99 baseline truth gate distinguishes --mir-c99, hosted native, fixture generator, and legacy C99"
