#!/usr/bin/env bash
#
# Focused real-CLI harness for the statement/CFG MIR-C99 shard.
#
# This gate intentionally uses ../uya/bin/uya directly.  It proves the shard has
# a real --mir-c99 CLI entry, a host-C99 compile/run oracle, and fail-closed
# evidence for statement/CFG shapes now covered by the structured CoreStmt lowering.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 shard compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-stmt-cfg-cli.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

statement_case="$tmp_dir/statement_return_literal.uya"
cfg_frontier_case="$tmp_dir/cfg_branch_loop_frontier.uya"
loop_edges_case="$tmp_dir/cfg_loop_break_continue_nested.uya"

cat >"$statement_case" <<'UYA'
export fn main() i32 {
    return 7;
}
UYA

cat >"$cfg_frontier_case" <<'UYA'
export fn main() i32 {
    var acc: i32 = 0;
    var i: i32 = 0;
    while i < 3 {
        {
            acc + 0;
        }
        if i < 2 {
            acc = acc + 2;
        } else {
            acc = acc + 1;
        }
        i = i + 1;
    }
    return acc;
}
UYA

cat >"$loop_edges_case" <<'UYA'
export fn main() i32 {
    var outer: i32 = 0;
    var total: i32 = 0;
    while outer < 3 {
        var inner: i32 = 0;
        while inner < 4 {
            inner = inner + 1;
            if inner < 2 {
                continue;
            }
            if inner < 3 {
                total = total + 10;
                break;
            }
            total = total + inner;
        }
        outer = outer + 1;
        if outer < 2 {
            continue;
        }
        total = total + outer;
    }
    return total;
}
UYA

mir_c="$tmp_dir/statement_return_literal.mir.c"
oracle_c="$tmp_dir/statement_return_literal.oracle.c"
mir_bin="$tmp_dir/statement_return_literal.mir"
oracle_bin="$tmp_dir/statement_return_literal.oracle"
mir_build_log="$tmp_dir/statement_return_literal.mir.build.log"
oracle_build_log="$tmp_dir/statement_return_literal.oracle.build.log"
cfg_c="$tmp_dir/cfg_branch_loop_frontier.mir.c"
cfg_oracle_c="$tmp_dir/cfg_branch_loop_frontier.oracle.c"
cfg_bin="$tmp_dir/cfg_branch_loop_frontier.mir"
cfg_oracle_bin="$tmp_dir/cfg_branch_loop_frontier.oracle"
cfg_build_log="$tmp_dir/cfg_branch_loop_frontier.mir.build.log"
cfg_oracle_build_log="$tmp_dir/cfg_branch_loop_frontier.oracle.build.log"
loop_edges_c="$tmp_dir/cfg_loop_break_continue_nested.mir.c"
loop_edges_oracle_c="$tmp_dir/cfg_loop_break_continue_nested.oracle.c"
loop_edges_bin="$tmp_dir/cfg_loop_break_continue_nested.mir"
loop_edges_oracle_bin="$tmp_dir/cfg_loop_break_continue_nested.oracle"
loop_edges_build_log="$tmp_dir/cfg_loop_break_continue_nested.mir.build.log"
loop_edges_oracle_build_log="$tmp_dir/cfg_loop_break_continue_nested.oracle.build.log"

"$COMPILER" build --mir-c99 "$statement_case" -o "$mir_c" --project-root "$REPO_ROOT" \
    >"$mir_build_log" 2>&1
"$COMPILER" build --c99 "$statement_case" -o "$oracle_c" --no-split-c --project-root "$REPO_ROOT" \
    >"$oracle_build_log" 2>&1

grep -q '\[MIR-C99\]' "$mir_build_log"
grep -q 'generated by MIR-C99 unit output writer' "$mir_c"
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$mir_build_log" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$mir_c"; then
    echo "error: real --mir-c99 statement shard showed legacy fallback evidence" >&2
    exit 1
fi

"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$mir_c" -o "$mir_bin"
"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$oracle_c" -o "$oracle_bin"

set +e
"$mir_bin" >"$tmp_dir/mir.stdout" 2>"$tmp_dir/mir.stderr"
mir_status=$?
"$oracle_bin" >"$tmp_dir/oracle.stdout" 2>"$tmp_dir/oracle.stderr"
oracle_status=$?
set -e

printf '%s\n' "$mir_status" >"$tmp_dir/mir.exit"
printf '%s\n' "$oracle_status" >"$tmp_dir/oracle.exit"
diff -u "$tmp_dir/oracle.stdout" "$tmp_dir/mir.stdout"
diff -u "$tmp_dir/oracle.stderr" "$tmp_dir/mir.stderr"
diff -u "$tmp_dir/oracle.exit" "$tmp_dir/mir.exit"

"$COMPILER" build --mir-c99 "$cfg_frontier_case" -o "$cfg_c" --project-root "$REPO_ROOT" \
    >"$cfg_build_log" 2>&1
"$COMPILER" build --c99 "$cfg_frontier_case" -o "$cfg_oracle_c" --no-split-c --project-root "$REPO_ROOT" \
    >"$cfg_oracle_build_log" 2>&1

grep -q '\[MIR-C99\]' "$cfg_build_log"
grep -q 'generated by MIR-C99 unit output writer' "$cfg_c"
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$cfg_build_log" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$cfg_c"; then
    echo "error: real --mir-c99 CFG shard showed legacy fallback evidence" >&2
    exit 1
fi

"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$cfg_c" -o "$cfg_bin"
"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$cfg_oracle_c" -o "$cfg_oracle_bin"

set +e
"$cfg_bin" >"$tmp_dir/cfg.mir.stdout" 2>"$tmp_dir/cfg.mir.stderr"
cfg_mir_status=$?
"$cfg_oracle_bin" >"$tmp_dir/cfg.oracle.stdout" 2>"$tmp_dir/cfg.oracle.stderr"
cfg_oracle_status=$?
set -e

printf '%s\n' "$cfg_mir_status" >"$tmp_dir/cfg.mir.exit"
printf '%s\n' "$cfg_oracle_status" >"$tmp_dir/cfg.oracle.exit"
diff -u "$tmp_dir/cfg.oracle.stdout" "$tmp_dir/cfg.mir.stdout"
diff -u "$tmp_dir/cfg.oracle.stderr" "$tmp_dir/cfg.mir.stderr"
diff -u "$tmp_dir/cfg.oracle.exit" "$tmp_dir/cfg.mir.exit"

"$COMPILER" build --mir-c99 "$loop_edges_case" -o "$loop_edges_c" --project-root "$REPO_ROOT" \
    >"$loop_edges_build_log" 2>&1
"$COMPILER" build --c99 "$loop_edges_case" -o "$loop_edges_oracle_c" --no-split-c --project-root "$REPO_ROOT" \
    >"$loop_edges_oracle_build_log" 2>&1

grep -q '\[MIR-C99\]' "$loop_edges_build_log"
grep -q 'generated by MIR-C99 unit output writer' "$loop_edges_c"
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$loop_edges_build_log" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$loop_edges_c"; then
    echo "error: real --mir-c99 loop-edge shard showed legacy fallback evidence" >&2
    exit 1
fi

"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$loop_edges_c" -o "$loop_edges_bin"
"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$loop_edges_oracle_c" -o "$loop_edges_oracle_bin"

set +e
"$loop_edges_bin" >"$tmp_dir/loop_edges.mir.stdout" 2>"$tmp_dir/loop_edges.mir.stderr"
loop_edges_mir_status=$?
"$loop_edges_oracle_bin" >"$tmp_dir/loop_edges.oracle.stdout" 2>"$tmp_dir/loop_edges.oracle.stderr"
loop_edges_oracle_status=$?
set -e

printf '%s\n' "$loop_edges_mir_status" >"$tmp_dir/loop_edges.mir.exit"
printf '%s\n' "$loop_edges_oracle_status" >"$tmp_dir/loop_edges.oracle.exit"
diff -u "$tmp_dir/loop_edges.oracle.stdout" "$tmp_dir/loop_edges.mir.stdout"
diff -u "$tmp_dir/loop_edges.oracle.stderr" "$tmp_dir/loop_edges.mir.stderr"
diff -u "$tmp_dir/loop_edges.oracle.exit" "$tmp_dir/loop_edges.mir.exit"

echo "OK: MIR-C99 statement/CFG shard real CLI harness used $COMPILER, compiled return/CFG/loop-edge C, and matched C99 oracle"
