#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d /tmp/uya-mir-c99-cli-distinct.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

hello_c="$tmp_dir/hello.c"
main_c="$tmp_dir/main.c"
hello_log="$tmp_dir/hello.log"
main_log="$tmp_dir/main.log"

"$REPO_ROOT/bin/uya" build --mir-c99 "$REPO_ROOT/examples/HelloWorld.uya" -o "$hello_c" >"$hello_log" 2>&1
"$REPO_ROOT/bin/uya" build --mir-c99 "$REPO_ROOT/src/main.uya" -o "$main_c" >"$main_log" 2>&1

grep -q '\[MIR-C99\]' "$hello_log"
grep -q '\[MIR-C99\]' "$main_log"
grep -q 'generated by MIR-C99 unit output writer' "$hello_c"
grep -q 'generated by MIR-C99 unit output writer' "$main_c"

if cmp -s "$hello_c" "$main_c"; then
    echo "error: different --mir-c99 inputs produced identical C output" >&2
    exit 1
fi

if grep -q 'C99 代码由 Uya Mini 编译器生成' "$hello_c" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$main_c"; then
    echo "error: --mir-c99 output still contains legacy C99 banner" >&2
    exit 1
fi

test -s "$hello_c"
test -s "$main_c"

echo "OK: uya build --mir-c99 emits distinct C for distinct inputs"
