#!/usr/bin/env bash
#
# Focused real-CLI harness for AST driver coverage in the MIR-C99 statement shard.
#
# This gate uses ../uya/bin/uya directly. It requires:
#   - simple range-for to compile via the real --mir-c99 route and match the C99 oracle;
#   - match/test frontiers to fail closed with explicit MIR-C99 capability diagnostics.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
HOST_CC="${HOST_CC:-cc}"

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 AST-driver compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

tmp_dir="$(mktemp -d /tmp/uya-mir-c99-ast-driver-cli.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

for_case="$tmp_dir/for_case.uya"
match_case="$tmp_dir/match_case.uya"
test_case="$tmp_dir/test_case.uya"

cat >"$for_case" <<'UYA'
export fn main() i32 {
    var sum: i32 = 0;
    for 0..4 |i| {
        sum = sum + i;
    }
    return sum;
}
UYA

cat >"$match_case" <<'UYA'
struct Payload {
    left: i32,
    right: i32,
}

union Value {
    number: i32,
    payload: Payload,
}

fn score(value: Value) i32 {
    return match value {
        .number(x) => x,
        .payload(p) => p.left + p.right,
    };
}

export fn main() i32 {
    const value: Value = Value.payload(Payload{ left: 11, right: 31 });
    const other: Value = Value.number(7);
    return score(value) + score(other);
}
UYA

cat >"$test_case" <<'UYA'
use std.testing.expect;

fn add(a: i32, b: i32) i32 {
    return a + b;
}

test "add works" {
    try expect(add(1, 2) == 3);
}
UYA

for_mir_c="$tmp_dir/for_case.mir.c"
for_oracle_c="$tmp_dir/for_case.oracle.c"
for_mir_bin="$tmp_dir/for_case.mir"
for_oracle_bin="$tmp_dir/for_case.oracle"
for_mir_log="$tmp_dir/for_case.mir.log"
for_oracle_log="$tmp_dir/for_case.oracle.log"

"$COMPILER" build --mir-c99 "$for_case" -o "$for_mir_c" --project-root "$REPO_ROOT" \
    >"$for_mir_log" 2>&1
"$COMPILER" build --c99 "$for_case" -o "$for_oracle_c" --no-split-c --project-root "$REPO_ROOT" \
    >"$for_oracle_log" 2>&1

grep -q '\[MIR-C99\]' "$for_mir_log"
grep -q 'generated by MIR-C99 unit output writer' "$for_mir_c"
if grep -Eiq 'fallback|legacy C99|codegen/c99|codegen\.c99|c99_codegen_generate|C99CodeGenerator' "$for_mir_log" ||
   grep -q 'C99 代码由 Uya Mini 编译器生成' "$for_mir_c"; then
    echo "error: AST for driver shard showed legacy fallback evidence" >&2
    exit 1
fi

"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$for_mir_c" -o "$for_mir_bin"
"$HOST_CC" -std=c99 -O2 -fno-builtin -Werror "$for_oracle_c" -o "$for_oracle_bin"

set +e
"$for_mir_bin" >"$tmp_dir/for.mir.stdout" 2>"$tmp_dir/for.mir.stderr"
for_mir_status=$?
"$for_oracle_bin" >"$tmp_dir/for.oracle.stdout" 2>"$tmp_dir/for.oracle.stderr"
for_oracle_status=$?
set -e

printf '%s\n' "$for_mir_status" >"$tmp_dir/for.mir.exit"
printf '%s\n' "$for_oracle_status" >"$tmp_dir/for.oracle.exit"
diff -u "$tmp_dir/for.oracle.stdout" "$tmp_dir/for.mir.stdout"
diff -u "$tmp_dir/for.oracle.stderr" "$tmp_dir/for.mir.stderr"
diff -u "$tmp_dir/for.oracle.exit" "$tmp_dir/for.mir.exit"

run_expect_diag() {
    local name="$1"
    local input="$2"
    local output="$3"
    local log="$4"
    local pattern="$5"

    set +e
    "$COMPILER" build --mir-c99 "$input" -o "$output" --project-root "$REPO_ROOT" \
        >"$log" 2>&1
    local status=$?
    set -e

    if [[ $status -eq 0 ]]; then
        echo "error: expected $name to fail closed under real --mir-c99" >&2
        exit 1
    fi
    grep -q '\[MIR-C99\]' "$log"
    grep -q "$pattern" "$log"
    if [[ -e "$output" && -s "$output" ]]; then
        echo "error: $name left a non-empty MIR-C99 output after fail-closed diagnostic" >&2
        exit 1
    fi
}

run_expect_diag "match driver" "$match_case" "$tmp_dir/match_case.mir.c" \
    "$tmp_dir/match_case.mir.log" \
    'mir_c99_capability_diagnostic: kind=AST_MATCH_EXPR reason=match_expr_requires_expr_value_place'

run_expect_diag "test driver" "$test_case" "$tmp_dir/test_case.mir.c" \
    "$tmp_dir/test_case.mir.log" \
    'mir_c99_capability_diagnostic: kind=AST_TEST_STMT reason=test_driver_not_lowered'

echo "OK: MIR-C99 AST driver shard real CLI harness covered range-for parity and explicit match/test diagnostics"
