#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d /tmp/uya-mir-c99-cli-stack-limit.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

out_c="$tmp_dir/stack_limit.c"
out_exe="$tmp_dir/stack_limit"
build_log="$tmp_dir/build.log"

"$REPO_ROOT/bin/uya" build --mir-c99 \
    "$REPO_ROOT/tests/fixtures/mir_c99_cmd_build_stack_limit_call.uya" \
    -o "$out_c" >"$build_log" 2>&1

grep -q '\[MIR-C99\]' "$build_log"
grep -q 'generated by MIR-C99 unit output writer' "$out_c"
grep -q 'uya_mir_fn_' "$out_c"

if grep -q 'C99 代码由 Uya Mini 编译器生成' "$out_c"; then
    echo "error: --mir-c99 produced legacy C99 output" >&2
    exit 1
fi

cc ${CFLAGS:- -std=c99 -O2 -fno-builtin -Werror} "$out_c" -o "$out_exe" ${LDFLAGS:-}

set +e
"$out_exe"
run_status=$?
set -e

if [[ "$run_status" -ne 4 ]]; then
    echo "error: stack-limit MIR-C99 program exited $run_status, expected 4" >&2
    exit 1
fi

echo "OK: uya build --mir-c99 stack-limit call fixture emits and runs MIR-C99 C"
