#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPILER="$REPO_ROOT/../uya/bin/uya"
tmp_dir="$(mktemp -d /tmp/uya-mir-c99-cli-helloworld.XXXXXX)"
trap 'rm -rf "$tmp_dir"' EXIT

out_c="$tmp_dir/helloworld.c"
out_exe="$tmp_dir/helloworld"
build_log="$tmp_dir/build.log"
run_log="$tmp_dir/run.log"

require_real_mir_output() {
    local label="$1"
    local log_file="$2"
    local output_c="$3"

    if ! grep -q '\[MIR-C99\]' "$log_file"; then
        echo "error: $label did not enter the real --mir-c99 route" >&2
        sed -n '1,160p' "$log_file" >&2 || true
        exit 1
    fi
    if ! grep -q 'generated by MIR-C99 unit output writer' "$output_c"; then
        echo "error: $label did not emit MIR-C99 unit-output C" >&2
        sed -n '1,60p' "$output_c" >&2 || true
        exit 1
    fi
    if grep -q 'C99 代码由 Uya Mini 编译器生成' "$output_c"; then
        echo "error: $label produced legacy C99 output" >&2
        sed -n '1,60p' "$output_c" >&2 || true
        exit 1
    fi
}

if [[ ! -x "$COMPILER" ]]; then
    echo "error: fixed MIR-C99 compiler is missing or not executable: $COMPILER" >&2
    exit 69
fi

"$COMPILER" build --mir-c99 "$REPO_ROOT/examples/HelloWorld.uya" -o "$out_c" >"$build_log" 2>&1

require_real_mir_output "HelloWorld CLI" "$build_log" "$out_c"
grep -q 'Hello, World!' "$out_c"

cc -std=c99 "$out_c" -o "$out_exe"
"$out_exe" >"$run_log"
grep -q 'Hello, World!' "$run_log"
grep -q '欢迎使用 Uya 编程语言！' "$run_log"

echo "OK: uya build --mir-c99 examples/HelloWorld.uya emits and runs MIR-C99 C"
