/* generated by MIR-C99 unit output writer */
/* mir-c99 includes */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>

/* mir-c99 typedefs */

/* mir-c99 extern prototypes */

/* mir-c99 function prototypes */

/* mir-c99 globals */

/* mir-c99 function bodies */
static void uya_mir_fn_7(void) {
bb0:
return;
}
