// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t test_basics() {
  int32_t x = 42;
  y = (y + 5);
  double f = 3.14159;
  uint8_t b = temp_-1;
  return ;
}

int32_t test_structs() {
  void p = Point;
}

int32_t test_slices() {
  void* arr = array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
  void* slice1 = slice(arr, 2, 5);
}

int32_t test_errors() {
  int32_t err_val = might_fail(temp_-1);
}

int32_t test_control_flow() {
  int32_t x = 10;
  if ((x > 5)) {
  result = (result + 10);
} else {
  result = (result + 0);
};
  while ((i < 3)) {
  result = (result + i);
  i = (i + 1);
};
  void* nums = array(1, 2, 3);
}

int32_t add(int32_t a, int32_t b) {
  return (a + b);
}

int32_t test_functions() {
  return add(15, 25);
}

int32_t test_interface() {
  void rect = Rectangle;
}

int32_t test_atomic() {
}

int32_t test_generic() {
  int32_t val = identity(42);
  return val;
}

int32_t test_macro() {
  int32_t x = 10;
  int32_t result = double_val(x);
  return result;
}

int32_t all_tests() {
  total = (total + test_basics());
  total = (total + test_structs());
  total = (total + test_slices());
  total = (total + test_errors());
  total = (total + test_control_flow());
  total = (total + test_functions());
  total = (total + test_interface());
  total = (total + test_atomic());
  total = (total + test_generic());
  total = (total + test_macro());
  return total;
}

int32_t main() {
  int32_t result = all_tests();
  return result;
}

