// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t test_basics() {
  int32_t x = temp_0;
  y = (y + temp_1);
  double f = temp_3;
  uint8_t b = temp_-1;
  return ;
}

int32_t test_structs() {
  void p = Point;
}

int32_t test_slices() {
  void* arr = array(temp_4, temp_5, temp_6, temp_7, temp_8, temp_9, temp_10, temp_11, temp_12, temp_13);
  void* slice1 = slice(arr, temp_14, temp_15);
}

int32_t test_errors() {
  int32_t err_val = might_fail(temp_-1);
}

int32_t test_control_flow() {
  int32_t x = temp_16;
  if ((x > temp_17)) {
  result = (result + temp_19);
} else {
  result = (result + temp_21);
};
  while ((i < temp_23)) {
  result = (result + i);
  i = (i + temp_26);
};
  void* nums = array(temp_28, temp_29, temp_30);
}

int32_t add(int32_t a, int32_t b) {
  return (a + b);
}

int32_t test_functions() {
  return add(temp_32, temp_33);
}

int32_t test_interface() {
  void rect = Rectangle;
}

int32_t test_atomic() {
}

int32_t test_generic() {
  int32_t val = identity(temp_34);
  return val;
}

int32_t test_macro() {
  int32_t x = temp_35;
  int32_t result = double_val(x);
  return result;
}

int32_t all_tests() {
  total = (total + test_basics());
  total = (total + test_structs());
  total = (total + test_slices());
  total = (total + test_errors());
  total = (total + test_control_flow());
  total = (total + test_functions());
  total = (total + test_interface());
  total = (total + test_atomic());
  total = (total + test_generic());
  total = (total + test_macro());
  return total;
}

int32_t main() {
  int32_t result = all_tests();
  return result;
}

