// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t test_basics() {
  int32_t x = temp_0;
  ;
  double f = temp_1;
  uint8_t b = temp_-1;
  return ;
}

int32_t test_structs() {
  void p = Point;
}

int32_t test_slices() {
  void* arr = array(temp_2, temp_3, temp_4, temp_5, temp_6, temp_7, temp_8, temp_9, temp_10, temp_11);
  void* slice1 = slice(arr, temp_12, temp_13);
}

int32_t test_errors() {
  int32_t err_val = might_fail(temp_-1);
}

int32_t test_control_flow() {
  int32_t x = temp_14;
  if ((x > temp_15)) {
  ;
} else {
  ;
};
  while ((i < temp_17)) {
  ;
  ;
};
  void* nums = array(temp_19, temp_20, temp_21);
}

int32_t add(int32_t a, int32_t b) {
  return (a + b);
}

int32_t test_functions() {
  return add(temp_23, temp_24);
}

int32_t test_interface() {
  void rect = Rectangle;
}

int32_t test_atomic() {
}

int32_t test_generic() {
  int32_t val = identity(temp_25);
  return val;
}

int32_t test_macro() {
  int32_t x = temp_26;
  int32_t result = double_val(x);
  return result;
}

int32_t all_tests() {
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  return total;
}

int32_t main() {
  int32_t result = all_tests();
  return result;
}

