// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t main() {
  int32_t x = 42;
  if ((x > 10)) {
  int32_t y = 20;
  while ((y > 0)) {
  y = (y - 1);
};
  return y;
} else {
  return x;
};
}

