// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t main() {
  int32_t x = temp_0;
  if ((x > temp_1)) {
  int32_t y = temp_3;
  return y;
} else {
  int32_t z = temp_4;
  return z;
};
}

