// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t main() {
  void* arr = array(1, 2, 3);
  for (/* for loop */) {
  if ((item > 1)) {
  return item;
};
};
  return 0;
}

