// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>

int32_t main() {
  void* arr = array(temp_0, temp_1, temp_2);
  for (/* for loop */) {
  return item;
};
  return temp_3;
}

