// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

// Error type definition (error codes are uint16_t)
typedef uint16_t error;

// Error union type definitions
typedef struct {
    bool is_error;
    union {
        int32_t success_value;
        uint16_t error_code;
    } value;
} ErrorUnion_int32_t;

typedef struct {
    bool is_error;
    union {
        uint8_t _void_placeholder;
        uint16_t error_code;
    } value;
} ErrorUnion_void;


typedef struct File {
  int32_t fd;
} File;

void drop(File self) {
  hello(10);
  close(self.fd);
_normal_return_drop:
  return;
}

typedef struct HeapBuffer {
  void* data;
  int32_t size;
} HeapBuffer;

void drop(HeapBuffer self) {
  hello(11);
  free(self.data);
_normal_return_drop:
  return;
}

void test_defer() {
  hello(20);
  // defer block (collected)
  // defer block (collected)
  hello(23);
_normal_return_test_defer:
  // Generated defer blocks in LIFO order
  // defer block 1
  hello(22);
  // defer block 0
  hello(21);
  return;
}

ErrorUnion_void test_errdefer() {
ErrorUnion_void  _return_test_errdefer;
  hello(30);
  // defer block (collected)
  // errdefer block (collected)
  _return_test_errdefer.is_error = false;
  _return_test_errdefer.value.success_value = 0;
  goto _check_error_return_test_errdefer;
_check_error_return_test_errdefer:
  if (_return_test_errdefer.is_error) {
    goto _error_return_test_errdefer;
  } else {
    goto _normal_return_test_errdefer;
  }

_error_return_test_errdefer:
  // Generated errdefer blocks in LIFO order (error return)
  // errdefer block 0
  hello(32);
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(31);
  return _return_test_errdefer;
_normal_return_test_errdefer:
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(31);
  return _return_test_errdefer;
}

ErrorUnion_int32_t test_combined() {
ErrorUnion_int32_t  _return_test_combined;
  hello(40);
  File f = (File){ .fd = open(temp_-1, 0)};
  HeapBuffer buf = (HeapBuffer){ .data = malloc(1024), .size = 1024};
  // defer block (collected)
  // errdefer block (collected)
  hello(43);
  _return_test_combined.is_error = false;
  _return_test_combined.value.success_value = 42;
  goto _check_error_return_test_combined;
_check_error_return_test_combined:
  if (_return_test_combined.is_error) {
    goto _error_return_test_combined;
  } else {
    goto _normal_return_test_combined;
  }

_error_return_test_combined:
  // Generated errdefer blocks in LIFO order (error return)
  // errdefer block 0
  hello(42);
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(41);
  // Generated drop calls in LIFO order
  drop(buf);
  drop(f);
  return _return_test_combined;
_normal_return_test_combined:
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(41);
  // Generated drop calls in LIFO order
  drop(buf);
  drop(f);
  return _return_test_combined;
}

ErrorUnion_int32_t test_combined_error() {
ErrorUnion_int32_t  _return_test_combined_error;
  hello(0);
  File f = (File){ .fd = open(temp_-1, 0)};
  HeapBuffer buf = (HeapBuffer){ .data = malloc(1024), .size = 1024};
  // defer block (collected)
  // errdefer block (collected)
  hello(3);
  _return_test_combined_error.is_error = false;
  _return_test_combined_error.value.success_value = 0;
  goto _check_error_return_test_combined_error;
_check_error_return_test_combined_error:
  if (_return_test_combined_error.is_error) {
    goto _error_return_test_combined_error;
  } else {
    goto _normal_return_test_combined_error;
  }

_error_return_test_combined_error:
  // Generated errdefer blocks in LIFO order (error return)
  // errdefer block 0
  hello(2);
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(1);
  // Generated drop calls in LIFO order
  drop(buf);
  drop(f);
  return _return_test_combined_error;
_normal_return_test_combined_error:
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(1);
  // Generated drop calls in LIFO order
  drop(buf);
  drop(f);
  return _return_test_combined_error;
}

void test_nested_drop() {
  hello(0);
  int32_t outer = 10;
  hello(1);
  {
    // defer block (collected)
    hello(2);
  };
  // defer block (collected)
  hello(4);
_normal_return_test_nested_drop:
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(3);
  return;
}

void hello(int32_t a) {
_normal_return_hello:
  return;
}

typedef struct SimpleStruct {
  int32_t value;
} SimpleStruct;

void drop(SimpleStruct self) {
  hello(50);
_normal_return_drop:
  return;
}

void test_array_drop() {
  hello(60);
  int32_t arr[] = {(SimpleStruct){ .value = 1}, (SimpleStruct){ .value = 2}, (SimpleStruct){ .value = 3}};
  hello(61);
  // defer block (collected)
  hello(63);
_normal_return_test_array_drop:
  // Generated defer blocks in LIFO order
  // defer block 0
  hello(62);
  return;
}

int32_t main() {
int32_t  _return_main;
  hello(100);
  test_defer();
  hello(101);
  test_errdefer();
_normal_return_main:
  return _return_main;
}

