/* generated by MIR-C99 unit output writer */
/* mir-c99 includes */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>

/* mir-c99 typedefs */

/* mir-c99 extern prototypes */

/* mir-c99 function prototypes */

/* mir-c99 globals */

/* mir-c99 function bodies */
static int32_t uya_mir_fn_3(void) {
int32_t tmp0 = 0;
bb0:
return 3;
}

int main(void) { return uya_mir_fn_3(); }
