// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

// Error type definition (error codes are uint32_t)
typedef uint32_t error;

// Slice type definition
// Generic slice structure for all slice types
struct slice {
    void* ptr;    // 8 bytes (64位) 或 4 bytes (32位)
    size_t len;   // 8 bytes (64位) 或 4 bytes (32位)
};

// Interface type definition
// Generic interface structure for all interface types
struct interface {
    void* vtable;  // 8 bytes (64位) 或 4 bytes (32位)
    void* data;    // 8 bytes (64位) 或 4 bytes (32位)
};

// Error union type definitions
struct error_union_int32_t {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
    int32_t value; // success value (only valid when error_id == 0)
};

struct error_union_void {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
};


typedef struct tuple_i32_bool {
  int32_t _0;
  _Bool _1;
} tuple_i32_bool;

typedef struct tuple_i32_f64_bool {
  int32_t _0;
  double _1;
  _Bool _2;
} tuple_i32_f64_bool;

// Forward declarations
int32_t main();

int32_t main() {
int32_t  _return_main;
  tuple_i32_bool pair = (tuple_i32_bool){ ._0 = 42, ._1 = true};
  tuple_i32_f64_bool triple = (tuple_i32_f64_bool){ ._0 = 10, ._1 = 3.14, ._2 = false};
  if (((pair._0 == 42) + (pair._1 == true))) {
  ({ int32_t __match_temp_0; if ((((triple._0 == 10) + (triple._1 == 3.14)) + (triple._2 == false))) { __match_temp_0 = temp_-1; } __match_temp_0; });
  };
  _return_main = 1;
  goto _normal_return_main;
_normal_return_main:
  // Generated drop calls in LIFO order
  drop_tuple_i32_f64_bool(&triple);
  drop_tuple_i32_bool(&pair);
  return _return_main;
}

