// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

// Error type definition (error codes are uint32_t)
typedef uint32_t error;

// Slice type definition
// Generic slice structure for all slice types
struct slice {
    void* ptr;    // 8 bytes (64位) 或 4 bytes (32位)
    size_t len;   // 8 bytes (64位) 或 4 bytes (32位)
};

// Interface type definition
// Generic interface structure for all interface types
struct interface {
    void* vtable;  // 8 bytes (64位) 或 4 bytes (32位)
    void* data;    // 8 bytes (64位) 或 4 bytes (32位)
};

// Error union type definitions
struct error_union_int32_t {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
    int32_t value; // success value (only valid when error_id == 0)
};

struct error_union_void {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
};


// Forward declarations
int32_t main();

int32_t main() {
int32_t  _return_main;
  void pair = (tuple_2){ ._0 = 42, ._1 = true};
  void triple = (tuple_3){ ._0 = 10, ._1 = 3.14, ._2 = false};
  if (((pair._0 == 42) + (pair._1 == true))) {
  if ((((triple._0 == 10) + (triple._1 == 3.14)) + (triple._2 == false))) {
  return 0;
};
  };
  _return_main = 1;
  goto _normal_return_main;
_normal_return_main:
  return _return_main;
}

