// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

// Error type definition (error codes are uint32_t)
typedef uint32_t error;

// Slice type definition
// Generic slice structure for all slice types
struct slice {
    void* ptr;    // 8 bytes (64位) 或 4 bytes (32位)
    size_t len;   // 8 bytes (64位) 或 4 bytes (32位)
};

// Interface type definition
// Generic interface structure for all interface types
struct interface {
    void* vtable;  // 8 bytes (64位) 或 4 bytes (32位)
    void* data;    // 8 bytes (64位) 或 4 bytes (32位)
};

// Error union type definitions
struct error_union_int32_t {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
    int32_t value; // success value (only valid when error_id == 0)
};

struct error_union_void {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
};


// Forward declarations
int32_t test();

int32_t test() {
int32_t  _return_test;
  int32_t x = 1;
  if ((x == 1)) {
  /* Unknown instruction type: 25 */;
  };
  _return_test = 0;
  goto _normal_return_test;
_normal_return_test:
  return _return_test;
}

