// Generated by Uya to C99 Compiler
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

// Error type definition (error codes are uint32_t)
typedef uint32_t error;

// Slice type definition
// Generic slice structure for all slice types
struct slice {
    void* ptr;    // 8 bytes (64位) 或 4 bytes (32位)
    size_t len;   // 8 bytes (64位) 或 4 bytes (32位)
};

// Interface type definition
// Generic interface structure for all interface types
struct interface {
    void* vtable;  // 8 bytes (64位) 或 4 bytes (32位)
    void* data;    // 8 bytes (64位) 或 4 bytes (32位)
};

// Error union type definitions
struct error_union_int32_t {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
    int32_t value; // success value (only valid when error_id == 0)
};

struct error_union_void {
    uint32_t error_id; // 0 = success (use value), non-zero = error (use error_id)
};


// Forward declarations
int32_t main();

int32_t main() {
int32_t  _return_main;
  int32_t x = 2;
  int32_t result;
  result = ({ int32_t __match_temp_0; if ((x == 1)) { __match_temp_0 = 10; }else if ((x == 2)) { __match_temp_0 = 20; }else if ((x == 3)) { __match_temp_0 = 30; }else if (1) { __match_temp_0 = 0; } __match_temp_0; });
  if ((result == 20)) {
  _return_main = 0;
  goto _normal_return_main;
} else {
  _return_main = 1;
  goto _normal_return_main;
  };
_normal_return_main:
  return _return_main;
}

