#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "用法: $0 <bin/cmd/build> <backup/cmd-build-<host>-<arch>-blob.c>" >&2
    exit 1
fi

INPUT_BIN="$1"
OUTPUT_C="$2"

if [[ ! -s "$INPUT_BIN" ]]; then
    echo "错误: 输入二进制不存在或为空: $INPUT_BIN" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT_C")"
TMP_C="${OUTPUT_C}.tmp"

{
    cat <<'EOF'
/* Generated by scripts/generate_cmd_build_blob_seed.sh.
 * Fast restore seed for bin/cmd/build on one exact host/arch.
 * The ordinary backup/cmd-build*.c source seed remains the portable C99 fallback.
 */
#include <stdint.h>
#include <stdio.h>
#include <sys/stat.h>

static const char cmd_build_blob_b64[] =
EOF
    base64 "$INPUT_BIN" | tr -d '\n' | fold -w 76 | sed 's/.*/"&"/'
    cat <<'EOF'
;

static int b64_value(int ch) {
    if (ch >= 'A' && ch <= 'Z') {
        return ch - 'A';
    }
    if (ch >= 'a' && ch <= 'z') {
        return ch - 'a' + 26;
    }
    if (ch >= '0' && ch <= '9') {
        return ch - '0' + 52;
    }
    if (ch == '+') {
        return 62;
    }
    if (ch == '/') {
        return 63;
    }
    return -1;
}

int main(int argc, char **argv) {
    const char *out_path = argc > 1 ? argv[1] : "bin/cmd/build";
    FILE *out = fopen(out_path, "wb");
    if (out == 0) {
        return 2;
    }

    uint32_t acc = 0;
    int bits = 0;
    const char *p = cmd_build_blob_b64;
    while (*p != 0) {
        if (*p == '=') {
            break;
        }
        const int v = b64_value((unsigned char)*p);
        if (v >= 0) {
            acc = (acc << 6) | (uint32_t)v;
            bits = bits + 6;
            if (bits >= 8) {
                bits = bits - 8;
                if (fputc((int)((acc >> bits) & 255u), out) == EOF) {
                    fclose(out);
                    return 3;
                }
            }
        }
        p = p + 1;
    }

    if (fclose(out) != 0) {
        return 4;
    }
    if (chmod(out_path, 0755) != 0) {
        return 5;
    }
    return 0;
}
EOF
} >"$TMP_C"

mv "$TMP_C" "$OUTPUT_C"
echo "生成 cmd/build blob seed: $OUTPUT_C"
